const NamePattern = @import("../../modules/person.zig").NamePattern;

pub const female_first_name = [_][]const u8{ "Amahle", "Ayanda", "Ayize", "Buhle", "Busisiwe", "Duduzile", "Hlengiwe", "Inyoni", "Isisa", "Jabulile", "Khanyisile", "Khethiwe", "Khulekani", "Lerato", "Liyana", "Lukhona", "Mbalienhle", "Mhambi", "Mthunzi", "Nandi", "Ndondoloza", "Nhlakanipho", "Nkosingiphile", "Nofoto", "Nokuthula", "Nolwazi", "Nomvula", "Nonhlanhla", "Nonjabulo", "Nonkululeko", "Nozipho", "Ntokozo", "Ntombizodwa", "Samukelisiwe", "Sibongile", "Sindisiwe", "Sinenhlanhla", "Siphephelo", "Sizakele", "Sizani", "Thabisa", "Thadie", "Thobeka", "Thulisile", "Uluthando", "Ulwazi", "Yibanathi", "Zanele", "Zobuhle" };

pub const first_name = [_][]const u8{ "Amahle", "Anele", "Ayanda", "Ayize", "Bafana", "Bangizwe", "Bhekimuzi", "Bhekizizwe", "Bhekumbuso", "Bonginkosi", "Buhle", "Busisiwe", "Duduzile", "Dumisani", "Fanyana", "Funani", "Gatsha", "Hlengiwe", "Inyoni", "Isisa", "Jabulile", "Kagiso", "Kgabu", "Khanyisile", "Khethiwe", "Khulekani", "Langa", "Lerato", "Linda", "Liyana", "Lukhona", "Lungelo", "Lwandle", "Mandla", "Maphikelela", "Mbalienhle", "Mhambi", "Mpilo", "Mpumelelo", "Msizi", "Mthunzi", "Musawenkosi", "Nandi", "Ndleleni", "Ndondoloza", "Nhlakanipho", "Nkanyezi", "Nkosenye", "Nkosingiphile", "Nkosinhle", "Nkosiyabo", "Nofoto", "Nokuthula", "Nolwazi", "Nomvula", "Nonhlanhla", "Nonjabulo", "Nonkululeko", "Nozipho", "Ntokozo", "Ntombizodwa", "Phila", "Philani", "Phiwokwakhe", "Samukelisiwe", "Sanele", "Sfiso", "Shaka", "Sibongile", "Sibusiso", "Sifiso", "Sindisiwe", "Sinenhlanhla", "Siphephelo", "Siphiwe", "Sipho", "Sithembiso", "Siyanda", "Sizakele", "Sizani", "Solomon", "Thabisa", "Thadie", "Thamsanqa", "Thando", "Themba", "Thobeka", "Thulani", "Thulisile", "Uluthando", "Ulwazi", "Velaphi", "Vusumuzi", "Yibanathi", "Zanele", "Zenzele", "Zithulele", "Zobuhle" };

pub const last_name = [_][]const u8{ "Bayeni", "Bengu", "Bhembe", "Bhengani", "Bhengu", "Bhuyeni", "Biyela", "Buthelezi", "Cebekhulu", "Cele", "Chiliza", "Delazy", "Dhlomo", "Dingiswayo", "Dlamini", "Dube", "Fuze", "Gabhezi", "Gama", "Gigaba", "Guliwe", "Gumede", "Gwacela", "Gwala", "Hlongwa", "Khawula", "Khumalo", "Khuzwayo", "Kunene", "Lamula", "Lembede", "Luthuli", "Mabhida", "Mabizela", "Maduma", "Magoza", "Malinga", "Maphisa", "Mashinini", "Mavundla", "Mbatha", "Mbende", "Mbuso", "Mehloluhlaza", "Mfeka", "Mfumu", "Mgenge", "Mkhatshwa", "Moseley", "Mqwebu", "Msibi", "Mthembu", "Mthethwa", "Mtolo", "Musi", "Ncusi", "Ndandali", "Ndebele", "Ngcolosi", "Ngema", "Ngubane", "Ngwazi", "Nhleko", "Nomvethe", "Nondlela", "Nonyana", "Nozulu", "Nsele", "Ntanzi", "Ntombela", "Nyanda", "Nzimande", "Radebe", "Seme", "Senzangakhona", "Shezi", "Sibiya", "Sithuli", "Siwele", "Siyaya", "Sokhela", "Sondisa", "Sothole", "Thoyana", "Thumbeza", "Thusi", "Tshabalala", "Vezi", "Vilakazi", "Wosiyane", "Yengwa", "Zondi", "Zondo", "Zubane", "Zuma", "Zungu" };

pub const last_name_pattern = [_]NamePattern{.{ .value = "{{person.last_name}}", .weight = 1 }};

pub const male_first_name = [_][]const u8{ "Bonginkosi", "Kagiso", "Bhekizizwe", "Bhekumbuso", "Shaka", "Funani", "Kgabu", "Solomon", "Gatsha", "Langa", "Phila", "Msizi", "Nkosiyabo", "Linda", "Mpilo", "Siyanda", "Nkanyezi", "Bafana", "Lwandle", "Sfiso", "Thulani", "Thando", "Sanele", "Anele", "Lungelo", "Dumisani", "Bangizwe", "Fanyana", "Bhekimuzi", "Mandla", "Maphikelela", "Mpumelelo", "Mthunzi", "Philani", "Musawenkosi", "Nkosenye", "Nkosinhle", "Phiwokwakhe", "Sifiso", "Zithulele", "Sithembiso", "Sipho", "Siphiwe", "Sibusiso", "Velaphi", "Thamsanqa", "Vusumuzi", "Themba", "Zenzele", "Ndleleni" };
