const NamePattern = @import("../../modules/person.zig").NamePattern;

pub const female_first_name = [_][]const u8{ "Aīda", "Akvelīna", "Albertīne", "Alvīne", "Amālija", "Astrīda", "Aurēlija", "Ārija", "Baņuta", "Bārbala", "Beāte", "Dagmāra", "Dainuvīte", "Dārta", "Diāna", "Dzirkstīte", "Dzīle", "Edīte", "Elfrīda", "Elīna", "Elīza", "Elmīra", "Elvīra", "Emīlija", "Ernestīne", "Evelīna", "Ērika", "Frīda", "Gabriela", "Gudrīte", "Ģertrūde", "Helēna", "Hermīne", "Ināra", "Ingrīda", "Ingūna", "Irēna", "Īrisa", "Janīna", "Jasmīna", "Jautrīte", "Judīte", "Justīne", "Jūlija", "Jūsma", "Karīna", "Katrīna", "Klāra", "Kristiāna", "Kristīne", "Lavīze", "Lāsma", "Leonīda", "Leontīne", "Liāna", "Liliāna", "Lība", "Līga", "Līksma", "Līna", "Līva", "Līvija", "Līze", "Luīze", "Lūcija", "Malvīne", "Māra", "Mārīte", "Mētra", "Modrīte", "Mudīte", "Olīvija", "Otīlija", "Patrīcija", "Paulīne", "Pārsla", "Regīna", "Renāte", "Rudīte", "Rūta", "Sabīne", "Sarmīte", "Saulcerīte", "Skaidrīte", "Spīdola", "Tamāra", "Terēze", "Tīna", "Trīne", "Undīne", "Valentīna", "Valērija", "Vēsma", "Vijolīte", "Vilhelmīne", "Vizbulīte", "Zeltīte", "Ziedīte", "Zigfrīda", "Zigrīda", "Zīle", "Žanete", "Žanna", "Ženija", "Žubīte" };

pub const female_last_name = [_][]const u8{ "Aigare", "Alksne", "Andersone", "Aspere", "Auziņa", "Ābele", "Āboliņa", "Āboltiņa", "Balode", "Beļavske", "Bergmane", "Bērziņa", "Bērzīte", "Birziņa", "Birzniece", "Bīriņa", "Blaua", "Blekte", "Breņķe", "Briede", "Brunkeviča", "Buile", "Buša", "Cauna", "Cālīte", "Cīrule", "Čudara", "Danielsone", "Dīriķe", "Dombrovska", "Dreimane", "Dzene", "Eglīte", "Endziņa", "Fogele", "Freimane", "Gaile", "Gailīte", "Gibala", "Graudiņa", "Gribuste", "Grīnberga", "Grūba", "Jansone", "Jēkabsone", "Jukuma", "Kalēja", "Kalniņa", "Karlsone", "Kauliņa", "Kārkliņa", "Kļaviņa", "Koha", "Koka", "Krance", "Krastiņa", "Kraule", "Krauze", "Krēsliņa", "Krieviņa", "Krieva", "Kronberga", "Krūmiņa", "Kulmane", "Laiviņa", "Landmane", "Lapiņa", "Lapsiņa", "Lasmane", "Lauberga", "Lāce", "Legzdiņa", "Lielmane", "Liepiņa", "Līce", "Līdaka", "Loča", "Lodiņa", "Lūse", "Matisone", "Medne", "Meiere", "Mekša", "Meldere", "Melngaile", "Mihailova", "Miķelsone", "Niedra", "Ose", "Ostrovska", "Ozere", "Ozoliņa", "Ozola", "Paltere", "Pavlovska", "Pence", "Petrovska", "Pērkona", "Pētersone", "Podziņa", "Pole", "Pretkalniņa", "Priedīte", "Puķīte", "Putniņa", "Riekstiņa", "Romanovska", "Rozenbaha", "Rozīte", "Rubene", "Rudzīte", "Runce", "Salmiņa", "Seržante", "Sietniece", "Siliņa", "Sīle", "Skudra", "Smuģe", "Sproģe", "Sprūde", "Strautiņa", "Strautmane", "Strazdiņa", "Širova", "Šīrante", "Šmite", "Šteina", "Tālberga", "Teicāne", "Tiltiņa", "Tīrele", "Tuča", "Ūdre", "Valtere", "Vasile", "Vecumniece", "Veinberga", "Veisa", "Vilka", "Vilsone", "Viļuma", "Vintere", "Vītiņa", "Vītoliņa", "Vītola", "Vītuma", "Volle", "Zariņa", "Zālīte", "Zeidmane", "Zeltiņa", "Ziemele", "Zībere", "Zunda", "Zvaigzne", "Zvejniece", "Zvinele", "Muceniece", "Dzirkale", "Arāja", "Sējēja", "Podniece", "Ratniece", "Deģe", "Bondare", "Sondore", "Namiķe", "Jumiķe", "Muižniece", "Bajāre", "Ķēniņa", "Ķeizare", "Barone", "Vaivade", "Zviedre", "Vāciete", "Lejiņa", "Vanaga", "Celma", "Liepa", "Kalna", "Celmiņa", "Lejniece", "Biseniece", "Kurzemniece", "Sauliete", "Pakalniete", "Pridāne", "Groduma", "Kalnāja", "Porgante", "Sukute", "Meškūna", "Rožkalne", "Mazjāne", "Latkovska", "Jankovska", "Šileiko", "Budreiko", "Ivanova", "Morozova", "Logina", "Gasjūne", "Pauļuka", "Sosāre", "Meškūne" };

pub const female_last_name_pattern = [_]NamePattern{ .{ .value = "{{person.female_last_name}}", .weight = 8 }, .{ .value = "{{person.female_last_name}}-{{person.female_last_name}}", .weight = 2 } };

pub const female_prefix = [_][]const u8{ "Prof.", "Dr.", "Biedrs" };

pub const first_name = [_][]const u8{ "Ainārs", "Akvelīna", "Albertīne", "Alfrēds", "Aloīzs", "Alvīne", "Amālija", "Andris", "Andžejs", "Andžs", "Anrijs", "Anšlavs", "Arkādijs", "Armīns", "Artūrs", "Arvīds", "Astrīda", "Aurēlija", "Aīda", "Aļģirds", "Aļģis", "Baņuta", "Beāte", "Boļeslavs", "Broņislavs", "Bārbala", "Dagmāra", "Dainuvīte", "Diāna", "Dzirkstīte", "Dzīle", "Dāgs", "Dārta", "Dāvids", "Dāvis", "Edgars", "Eduards", "Edvīns", "Edīte", "Edžus", "Egīls", "Einārs", "Eižens", "Elfrīda", "Elmārs", "Elmīra", "Elvīra", "Elīna", "Elīza", "Emīlija", "Emīls", "Ermīns", "Ernestīne", "Ervīns", "Evelīna", "Frīda", "Gabriela", "Gudrīte", "Gunārs", "Helēna", "Hermīne", "Ilgmārs", "Ilmārs", "Indriķis", "Ingmārs", "Ingrīda", "Ingūna", "Ināra", "Inārs", "Irēna", "Janīna", "Jasmīna", "Jautrīte", "Jevgeņijs", "Judīte", "Jurģis", "Justīne", "Jānis", "Jāzeps", "Jēkabs", "Jūlija", "Jūlijs", "Jūsma", "Karīna", "Katrīna", "Klāra", "Klāvs", "Konrāds", "Konstantīns", "Kristiāna", "Kristiāns", "Kristīne", "Krišjānis", "Krišs", "Kārlis", "Lavīze", "Leontīne", "Leonīda", "Leonīds", "Liliāna", "Liāna", "Luīze", "Lāsma", "Lība", "Līga", "Līksma", "Līna", "Līva", "Līvija", "Līze", "Lūcija", "Malvīne", "Marģers", "Matīss", "Miķelis", "Modrīte", "Monvīds", "Mudīte", "Māra", "Mārcis", "Māris", "Mārtiņš", "Mārīte", "Mētra", "Niklāvs", "Ojārs", "Olīvija", "Otīlija", "Oļegs", "Oļģerts", "Patrīcija", "Paulīne", "Pārsla", "Pāvils", "Pēteris", "Regnārs", "Regīna", "Renārs", "Renāte", "Ričards", "Romāns", "Rudīte", "Rūdis", "Rūdolfs", "Rūsiņš", "Rūta", "Sabīne", "Sarmīte", "Saulcerīte", "Skaidrīte", "Spīdola", "Tamāra", "Terēze", "Trīne", "Tālis", "Tālivaldis", "Tālrīts", "Tīna", "Undīne", "Uģis", "Valdemārs", "Valentīna", "Valentīns", "Valērija", "Valērijs", "Vijolīte", "Vilhelmīne", "Vilmārs", "Vitālijs", "Vizbulīte", "Voldemārs", "Vēsma", "Zeltīte", "Ziedīte", "Zigfrīda", "Zigfrīds", "Zigmārs", "Zigrīda", "Zīle", "Ādams", "Ādolfs", "Ārija", "Ārijs", "Āris", "Ērika", "Ēriks", "Ēvalds", "Ģederts", "Ģertrūde", "Ģirts", "Īrisa", "Žanete", "Žanis", "Žanna", "Ženija", "Žubīte" };

pub const male_first_name = [_][]const u8{ "Ainārs", "Alfrēds", "Aloīzs", "Aļģirds", "Aļģis", "Andris", "Andžejs", "Andžs", "Anrijs", "Anšlavs", "Arkādijs", "Armīns", "Artūrs", "Arvīds", "Ādams", "Ādolfs", "Ārijs", "Āris", "Boļeslavs", "Broņislavs", "Dāgs", "Dāvids", "Dāvis", "Edgars", "Edvīns", "Eduards", "Edžus", "Egīls", "Einārs", "Eižens", "Elmārs", "Emīls", "Ermīns", "Ervīns", "Ēriks", "Ēvalds", "Gunārs", "Ģederts", "Ģirts", "Ilgmārs", "Ilmārs", "Inārs", "Indriķis", "Ingmārs", "Jānis", "Jāzeps", "Jevgeņijs", "Jēkabs", "Jurģis", "Jūlijs", "Kārlis", "Klāvs", "Konrāds", "Konstantīns", "Kristiāns", "Krišjānis", "Krišs", "Leonīds", "Marģers", "Matīss", "Mārcis", "Māris", "Mārtiņš", "Miķelis", "Monvīds", "Niklāvs", "Ojārs", "Oļegs", "Oļģerts", "Pāvils", "Pēteris", "Regnārs", "Renārs", "Ričards", "Romāns", "Rūdis", "Rūdolfs", "Rūsiņš", "Tālis", "Tālivaldis", "Tālrīts", "Uģis", "Valdemārs", "Valentīns", "Valērijs", "Vilmārs", "Vitālijs", "Voldemārs", "Zigfrīds", "Zigmārs", "Žanis" };

pub const male_last_name = [_][]const u8{ "Aigars", "Alksnis", "Andersons", "Aspers", "Auziņš", "Ābele", "Āboliņš", "Āboltiņš", "Balodis", "Beļavskis", "Bergmanis", "Bērziņš", "Bērzīts", "Birziņš", "Birznieks", "Bīriņš", "Blaus", "Blekte", "Breņķis", "Briedis", "Brunkevičs", "Builis", "Bušs", "Caune", "Cālītis", "Cīrulis", "Čudars", "Danielsons", "Dīriķis", "Dombrovskis", "Dreimanis", "Dzenis", "Eglītis", "Endziņš", "Fogelis", "Freimanis", "Gailis", "Gailītis", "Gibala", "Graudiņš", "Gribusts", "Grīnbergs", "Grūbe", "Jansons", "Jēkabsons", "Jukums", "Kalējs", "Kalniņš", "Karlsons", "Kauliņš", "Kārkliņš", "Kļaviņš", "Kohs", "Koks", "Krancis", "Krastiņš", "Kraulis", "Krauze", "Krēsliņš", "Krieviņš", "Krievs", "Kronbergs", "Krūmiņš", "Kulmanis", "Laiviņš", "Landmanis", "Lapiņš", "Lapsiņš", "Lasmanis", "Laubergs", "Lācis", "Legzdiņš", "Lielmanis", "Liepiņš", "Līcis", "Līdaks", "Ločs", "Lodiņš", "Lūsis", "Matisons", "Mednis", "Meiers", "Mekšs", "Melderis", "Melngailis", "Mihailovs", "Miķelsons", "Niedra", "Osis", "Ostrovskis", "Ozers", "Ozoliņš", "Ozols", "Palters", "Pavlovskis", "Pencis", "Petrovskis", "Pērkons", "Pētersons", "Podziņš", "Polis", "Pretkalniņš", "Priedītis", "Puķītis", "Putniņš", "Riekstiņš", "Romanovskis", "Rozenbahs", "Rozītis", "Rubenis", "Rudzītis", "Runcis", "Salmiņš", "Seržants", "Sietnieks", "Siliņš", "Sīlis", "Skudra", "Smuģis", "Sproģis", "Sprūde", "Strautiņš", "Strautmanis", "Strazdiņš", "Širovs", "Šīrants", "Šmits", "Šteins", "Tālbergs", "Teicāns", "Tiltiņš", "Tīrelis", "Tučs", "Ūdris", "Valters", "Vasils", "Vecumnieks", "Veinbergs", "Veiss", "Vilks", "Vilsons", "Viļums", "Vinters", "Vītiņš", "Vītoliņš", "Vītols", "Vītums", "Vollis", "Zariņš", "Zālītis", "Zeidmanis", "Zeltiņš", "Ziemelis", "Zībers", "Zunda", "Zvaigzne", "Zvejnieks", "Zvinelis", "Mucenieks", "Dzirkalis", "Arājs", "Sējējs", "Podnieks", "Ratnieks", "Deģis", "Bondars", "Sondors", "Namiķis", "Jumiķis", "Muižnieks", "Bajārs", "Ķēniņš", "Ķeizars", "Barons", "Vaivads", "Zviedrs", "Vācietis", "Lejiņš", "Vanags", "Celms", "Liepa", "Kalns", "Celmiņš", "Lejnieks", "Bisenieks", "Kurzemnieks", "Saulietis", "Pakalnietis", "Pridāns", "Grodums", "Kalnājs", "Porgants", "Sukuts", "Meškūns", "Rožkalns", "Mazjānis", "Latkovskis", "Jankovskis", "Šileiko", "Budreiko", "Ivanovs", "Morozovs", "Logins", "Gasjūns", "Pauļuks", "Sosārs" };

pub const male_last_name_pattern = [_]NamePattern{ .{ .value = "{{person.male_last_name}}", .weight = 8 }, .{ .value = "{{person.male_last_name}}-{{person.male_last_name}}", .weight = 2 } };

pub const male_prefix = [_][]const u8{ "Prof.", "Dr.", "Biedrs" };

pub const name = [_]NamePattern{ .{ .value = "{{person.prefix}} {{person.firstName}} {{person.lastName}}", .weight = 1 }, .{ .value = "{{person.firstName}} {{person.lastName}} {{person.suffix}}", .weight = 1 }, .{ .value = "{{person.firstName}} {{person.lastName}}", .weight = 7 } };

pub const prefix = [_][]const u8{ "Biedrs", "Dr.", "Prof." };

pub const suffix = [_][]const u8{ "k-dze", "kundze" };

pub const title = .{ .descriptor = [_][]const u8{ "Galvenais", "Vecākais", "Tiešo", "Korporatīvās", "Produktu", "Reģionālās", "Rajona", "Klientu", "Investīciju", "Starptautiskās", "Iekšējās", "Personu" }, .level = [_][]const u8{ "risinājumu", "programmu", "drošības", "izpētes", "mārketinga", "vadības", "izveides", "integrāciju", "funkcionalitātes", "taktikas", "identitātes", "tirgus", "grupas", "nodaļas", "pielietojumu", "optimizācijas", "operāciju", "infrastruktūras", "intraneta", "sakaru", "kvalitātes", "mobilitātes", "kontu", "datu", "kreatīvais", "konfigurācijas", "grāmatojumu", "sadarbības", "lietojamības", "mērījumu" }, .job = [_][]const u8{ "uzraugs", "vadītājs", "pārstāvis", "oficieris", "menedžers", "inženieris", "speciālists", "direktors", "koordinators", "administrators", "arhitekts", "analītiķis", "dizainers", "plānotājs", "pārraugs", "tehniķis", "izstrādātājs", "producents", "konsultants", "asistents", "aģents", "stratēģis" } };
