pub const adjective = [_][]const u8{ "altkvalita", "aŭtomata", "bludenta", "cifereca", "ĉefa", "defaŭlta", "enreta", "helpa", "hibrida", "interna", "malfermitkoda", "nesinkrona", "neŭrona", "nuba", "optika", "plenekrana", "plurbajta", "plurplatforma", "portebla", "realtempa", "redunda", "sendrata", "solidstata", "universala", "virtuala" };

pub const ingverb = [_][]const u8{ "analizado", "arĥivado", "bitigado", "densigado", "enigado", "generado", "indeksado", "interŝanĝado", "kalkulado", "kodrompado", "kodumado", "kompilado", "konektado", "kopiado", "muntado", "nuligado", "preterpasado", "programado", "restartigado", "savkopiado", "sinkronigado", "sintezado", "transpasado", "transsendado", "validigado" };

pub const noun = [_][]const u8{ "alarmo", "aplikaĵo", "bendlarĝo", "buso", "cirkvito", "datumbazo", "datumcentro", "disko", "dosiero", "ekrano", "fajroŝirmilo", "fluo", "interfaco", "karto", "kondensilo", "konektilo", "konektingo", "konekto", "matrico", "operaciumo", "panelo", "pelilo", "programo", "protokolo", "rastrumero", "reto", "sentilo", "servilo", "sistemo", "transsendilo" };

pub const phrase = [_][]const u8{ "Se ni povus {{verb}} la {{noun}}n, ni povus aliri la {{abbreviation}}-{{noun}}n per la {{adjective}} {{abbreviation}}-{{noun}}!", "Ni devas {{verb}} la {{adjective}}n {{abbreviation}}-{{noun}}n!", "Provu {{verb}} la {{abbreviation}}-{{noun}}n, eble ni sukcesos {{verb}} la {{adjective}}n {{noun}}n!", "Vi ne povas {{verb}} la {{noun}}n sen {{ingverb}} de la {{adjective}} {{abbreviation}}-{{noun}}!", "Uzu la {{adjective}}n {{abbreviation}}-{{noun}}n, poste vi povos {{verb}} la {{adjective}}n {{noun}}n!", "La {{abbreviation}}-{{noun}} ne funkcias, provu {{verb}} la {{adjective}}n {{noun}}n, por ke ni povu {{verb}} la {{abbreviation}}-{{noun}}n!", "Ne funkcios {{ingverb}} de la {{noun}}, ni devas {{verb}} la {{adjective}}n {{abbreviation}}-{{noun}}n!", "Mi provos {{verb}} la {{adjective}}n {{abbreviation}}-{{noun}}n, tio devus {{verb}} la {{abbreviation}}-{{noun}}n!", "Ne gravas, se ni ne povus {{verb}} la {{noun}}n, ni devas nur {{verb}} la {{adjective}}n {{abbreviation}}-{{noun}}!" };

pub const verb = [_][]const u8{ "analizi", "arĥivi", "bitigi", "densigi", "enigi", "generi", "indeksi", "interŝanĝi", "kalkuli", "kodrompi", "kodumi", "kompili", "konekti", "kopii", "munti", "nuligi", "preterpasi", "programi", "restartigi", "savkopii", "sinkronigi", "sintezi", "transpasi", "transsendi", "validigi" };
