const NamePattern = @import("../../modules/person.zig").NamePattern;

pub const bio_part = [_][]const u8{ "aktivulo", "aktoro", "akuŝisto", "amiko", "artisto", "astronomo", "aŭtoro", "bakisto", "biciklisto", "bloganto", "ĉokoladisto", "dancisto", "dentisto", "desegnisto", "dezajnisto", "dietisto", "diplomato", "direktoro", "edukisto", "ekologo", "eldonisto", "entreprenisto", "esperantisto", "esploristo", "estrarano", "farbisto", "fervojisto", "filmamanto", "filmisto", "filozofo", "fizikisto", "fondinto", "fotisto", "gepatro", "gimnasto", "ginekologo", "gitaristo", "GLAT-ulo", "gvidanto", "ĥemiisto", "ĥirurgo", "idisto", "inĝeniero", "instruisto", "inventinto", "ĵurnalisto", "kantisto", "kasisto", "komercisto", "komitatano", "kreanto", "kuiristo", "kuracisto", "laboristo", "leganto", "lingvisto", "ludanto", "manlaboristo", "maristo", "matematikisto", "modelo", "muzikisto", "nerdo", "novulo", "oficisto", "okulkuracisto", "parolanto", "patrioto", "pensiulo", "pentristo", "pianisto", "poligloto", "politikisto", "poŝtisto", "presisto", "prezidanto", "programisto", "psikologo", "revulo", "sciencisto", "sekretario", "senlaborulo", "staĝanto", "stenografisto", "studento", "tabloludanto", "terapiisto", "terkulturisto", "trejnisto", "urbestro", "vartisto", "vendisto", "verdulo", "verkisto", "veterano", "videobloganto", "videoludanto", "vojaĝanto", "volapukisto", "volontulo" };

pub const bio_pattern = [_][]const u8{ "{{person.bio_part}}", "{{person.bio_part}} {{internet.emoji}}", "{{person.bio_part}}, {{person.bio_part}}", "{{person.bio_part}}, {{person.bio_part}} {{internet.emoji}}", "{{person.bio_part}}, {{person.bio_part}}, {{person.bio_part}}", "{{person.bio_part}}, {{person.bio_part}}, {{person.bio_part}} {{internet.emoji}}" };

pub const female_first_name = [_][]const u8{ "Agripino", "Albertino", "Alcestiso", "Alekso", "Alfonsino", "Alico", "Amalio", "Anastazio", "Angelino", "Anno", "Aŭgustino", "Baŭcido", "Beatrico", "Berenico", "Berto", "Brigito", "Ĉarloto", "Cecilio", "Doroteo", "Eleonoro", "Elizabeto", "Elizo", "Emilio", "Ernestino", "Evelino", "Evo", "Fatimo", "Filipino", "Gertrudo", "Gustavino", "Hedvigo", "Heleno", "Henrieto", "Hermiono", "Ĥimeno", "Ilzo", "Ireno", "Izoldo", "Jakelino", "Jakobino", "Janjo", "Johanino", "Joŝiko", "Jozefino", "Judito", "Julieto", "Juliino", "Karmeno", "Karolino", "Katerino", "Klanjo", "Klaro", "Klaŭdino", "Klementino", "Kleopatro", "Klitemnestro", "Klotildo", "Kreuzo", "Krimhildo", "Kristino", "Ksantipo", "Laŭro", "Leopoldino", "Lilio", "Ludovikino", "Magdaleno", "Malvino", "Manjo", "Margareto", "Marinjo", "Mario", "Miriamo", "Mirto", "Moniko", "Olimpio", "Paŭlino", "Perpetuo", "Raĥelo", "Rebeko", "Rozo", "Sabino", "Sofinjo", "Sofio", "Sonjo", "Stefanino", "Susano", "Terezo", "Ursulo", "Veroniko", "Vilhelmino" };

pub const female_prefix = [_][]const u8{ "s-ino", "d-ro", "d-ino", "prof." };

pub const first_name = [_][]const u8{ "Abrahamo", "Adolfo", "Agripino", "Albertino", "Alcestiso", "Aleksandro", "Alekso", "Alfonsino", "Alfredo", "Alico", "Amalio", "Anastazio", "Andreo", "Angelino", "Anno", "Antono", "Anĝelo", "Arturo", "Aŭgustino", "Aŭguĉjo", "Bartolomeo", "Baŭcido", "Beatrico", "Berenico", "Bertilo", "Berto", "Brigito", "Bruno", "Cecilio", "Dagoberto", "Danielo", "Donaldo", "Doroteo", "Edgaro", "Eduardo", "Eleonoro", "Elizabeto", "Elizo", "Emiliano", "Emilio", "Ernestino", "Ernesto", "Erneĉjo", "Evelino", "Evo", "Fatimo", "Ferdinando", "Fernando", "Filipino", "Francisko", "Frederiko", "Gabrielo", "Gastono", "Georgo", "Gertrudo", "Gilberto", "Gustavino", "Gustavo", "Hasano", "Hedvigo", "Hektoro", "Heleno", "Henrieto", "Hermiono", "Huberto", "Hugo", "Ilzo", "Ireno", "Ivano", "Ivo", "Izako", "Izoldo", "Iŝmaelo", "Jakelino", "Jakobino", "Jakobo", "Janjo", "Jano", "Joakimo", "Johanino", "Johano", "Johanĉjo", "Jonatano", "Josuo", "Jozefino", "Jozefo", "Joĉjo", "Joŝiko", "Judito", "Julieto", "Juliino", "Justeno", "Karlo", "Karmeno", "Karolino", "Karolo", "Katerino", "Klanjo", "Klaro", "Klaŭdino", "Klaŭdo", "Klementino", "Kleopatro", "Klitemnestro", "Klotildo", "Knuto", "Kreuzo", "Krimhildo", "Kristino", "Ksantipo", "Lamberto", "Laŭrenco", "Laŭro", "Leono", "Leopoldino", "Leopoldo", "Lilio", "Ludovikino", "Ludoviko", "Luko", "Magdaleno", "Maksimo", "Makso", "Malvino", "Manjo", "Margareto", "Marinjo", "Mario", "Marko", "Marteno", "Mateo", "Miriamo", "Mirto", "Miĉjo", "Moniko", "Moseo", "Muhamado", "Nikolao", "Nikolĉjo", "Noaĥo", "Olimpio", "Oskaro", "Osvaldo", "Pablo", "Patriko", "Paŭlino", "Perpetuo", "Petro", "Rafaelo", "Raĥelo", "Rebeko", "Roberto", "Rolando", "Rozo", "Rudolfo", "Sabino", "Samuelo", "Sebastiano", "Simono", "Sofinjo", "Sofio", "Sonjo", "Stanislao", "Stefanino", "Stefano", "Susano", "Terezo", "Tiberio", "Tomaso", "Ursulo", "Veroniko", "Viktoro", "Vilhelmino", "Vilhelmo", "Vilĉjo", "Vladimiro", "Ĉarloto", "Ĥimeno", "Ĵeromo" };

pub const gender = [_][]const u8{ "androgino", "cisgenra virino", "cisgenra viro", "cisgenrulo", "cisulo", "cisvirino", "cisviro", "dugenrulo", "duspiritulo", "genrokviro", "hiĝro", "interseksulo", "kviro", "neduumulo", "sengenrulo", "transgenra virino", "transgenra viro", "transgenrulo", "transulo", "transvirino", "transviro", "travesĉio", "trigenrulo", "virino", "viro" };

pub const last_name = [_][]const u8{ "Atanasov", "Auld", "Aymonier", "Baghy", "Bailey", "Bastien", "Beauchemin", "Becker", "Bein", "Bennemann", "Bicknell", "Boirac", "Boulton", "Bourlet", "Bouwes", "Bulthuis", "Cart", "Cederblad", "Christaller", "Corret", "Cseh", "Dirksen", "Dor", "Droogendijk", "Elb", "Ellis", "Enderby", "Engholm", "Evstifejev", "Frenkel", "Gasse", "Geurts", "Grabowski", "Grosjean", "Hermelin", "Hideo", "Hodler", "Holmes", "Huet", "Isbrücker", "Junck", "Kalocsay", "Kotzin", "Krijt", "Kriss", "Kühnl", "Kürsteiner", "Lagrange", "Lapenna", "Lengyel", "Liniger", "Lippmann", "Luyken", "Makkink", "Malmgren", "Matton", "Meyer", "Migliorini", "Millidge", "Milsom", "Mirski", "Moscheles", "Motteau", "Mudie", "Mybs", "Noël", "Nourmont", "Nylén", "Pikover", "Piron", "Pollen", "Privat", "Renard", "Rhodes", "Riisberg", "Rittenberg", "Rossetti", "Sabadell", "Schafer", "Schleyer", "Schmid", "Schmidt", "Schröder", "Schulz", "Schwartz", "Setälä", "Simon", "Sofer", "Stamatiadis", "Stettler", "Sturmer", "Thisell", "Uitterdijk", "Vallienne", "Verax", "Villanueva", "Wackrill", "Zaleski", "Zamenhof", "Zimmermann" };

pub const last_name_pattern = [_]NamePattern{ .{ .value = "{{person.last_name}}", .weight = 95 }, .{ .value = "{{person.last_name}}-{{person.last_name}}", .weight = 5 } };

pub const male_first_name = [_][]const u8{ "Abrahamo", "Adolfo", "Aleksandro", "Alekso", "Alfredo", "Andreo", "Anĝelo", "Antono", "Arturo", "Aŭguĉjo", "Bartolomeo", "Bertilo", "Bruno", "Dagoberto", "Danielo", "Donaldo", "Edgaro", "Eduardo", "Emiliano", "Erneĉjo", "Ernesto", "Ferdinando", "Fernando", "Francisko", "Frederiko", "Gabrielo", "Gastono", "Georgo", "Gilberto", "Gustavo", "Hasano", "Hektoro", "Huberto", "Hugo", "Iŝmaelo", "Ivano", "Ivo", "Izako", "Jakobo", "Jano", "Ĵeromo", "Joakimo", "Joĉjo", "Johanĉjo", "Johano", "Jonatano", "Josuo", "Jozefo", "Justeno", "Karlo", "Karolo", "Klaŭdo", "Knuto", "Lamberto", "Laŭrenco", "Leono", "Leopoldo", "Ludoviko", "Luko", "Maksimo", "Makso", "Marko", "Marteno", "Mateo", "Miĉjo", "Moseo", "Muhamado", "Nikolao", "Nikolĉjo", "Noaĥo", "Oskaro", "Osvaldo", "Pablo", "Patriko", "Petro", "Rafaelo", "Roberto", "Rolando", "Rudolfo", "Samuelo", "Sebastiano", "Simono", "Stanislao", "Stefano", "Tiberio", "Tomaso", "Viktoro", "Vilĉjo", "Vilhelmo", "Vladimiro" };

pub const male_prefix = [_][]const u8{ "s-ro", "d-ro", "prof." };

pub const name = [_]NamePattern{ .{ .value = "{{person.firstName}} {{person.lastName}}", .weight = 7 }, .{ .value = "{{person.prefix}} {{person.firstName}} {{person.lastName}}", .weight = 1 } };

pub const prefix = [_][]const u8{ "d-ino", "d-ro", "prof.", "s-ino", "s-ro" };

pub const sex = [_][]const u8{ "vira", "ina" };

pub const western_zodiac_sign = [_][]const u8{ "Akvisto", "Fiŝoj", "Ŝafo", "Bovo", "Ĝemeloj", "Kankro", "Leono", "Virgulo", "Pesilo", "Skorpio", "Pafisto", "Kaprikorno" };
