const NamePattern = @import("../../modules/person.zig").NamePattern;

pub const female_first_name = [_][]const u8{ "Hanna", "Anna", "Zoé", "Léna", "Luca", "Emma", "Zsófia", "Boglárka", "Lili", "Mira", "Lilien", "Nóra", "Laura", "Lara", "Maja", "Fanni", "Jázmin", "Izabella", "Olívia", "Sára", "Gréta", "Alíz", "Adél", "Lilla", "Liza", "Flóra", "Dorka", "Zselyke", "Dóra", "Csenge", "Janka", "Liliána", "Viktória", "Szofia", "Réka", "Panna", "Petra", "Dorina", "Natasa", "Blanka", "Eszter", "Noémi", "Emília", "Bianka", "Kamilla", "Szófia", "Vivien", "Rebeka", "Elizabet", "Linett", "Szofi", "Júlia", "Szonja", "Abigél", "Mia", "Bella", "Lia", "Natália", "Tamara", "Lotti", "Róza", "Amira", "Eliza", "Panka", "Milla", "Zorka", "Hanga", "Nara", "Norina", "Fruzsina", "Mirella", "Dorottya", "Boróka", "Emili", "Regina", "Johanna", "Alexandra", "Diána", "Elena", "Kinga", "Hédi", "Borbála", "Emese", "Bíborka", "Barbara", "Letícia", "Lujza", "Zita", "Kincső", "Nina", "Vanda", "Veronika", "Zara", "Lana", "Lora", "Kiara", "Lívia", "Rozina", "Zejnep", "Virág" };

pub const female_prefix = [_][]const u8{ "Dr.", "Prof." };

pub const first_name = [_][]const u8{ "Abigél", "Adrián", "Adél", "Alex", "Alexander", "Alexandra", "Alíz", "Amira", "András", "Anna", "Attila", "Balázs", "Barbara", "Barnabás", "Bella", "Bence", "Bende", "Bendegúz", "Benedek", "Benett", "Benjamin", "Benjámin", "Bertalan", "Bianka", "Blanka", "Boglárka", "Boldizsár", "Borbála", "Boróka", "Botond", "Brájen", "Bálint", "Bíborka", "Csaba", "Csanád", "Csenge", "Csongor", "Denisz", "Diána", "Dominik", "Donát", "Dorina", "Dorián", "Dorka", "Dorottya", "Dániel", "Dávid", "Dóra", "Elena", "Eliza", "Elizabet", "Emese", "Emili", "Emma", "Emília", "Erik", "Eszter", "Fanni", "Ferenc", "Flóra", "Fruzsina", "Gellért", "Gergely", "Gergő", "Gréta", "György", "Gábor", "Hanga", "Hanna", "Hunor", "Hédi", "Imre", "István", "Iván", "Izabella", "Janka", "Johanna", "János", "Jázmin", "József", "Júlia", "Kamilla", "Kende", "Kevin", "Kiara", "Kincső", "Kinga", "Kolos", "Kornél", "Kristóf", "Krisztián", "Krisztofer", "Lajos", "Lana", "Lara", "Laura", "Laurent", "Letícia", "Levente", "Lia", "Lili", "Lilien", "Liliána", "Lilla", "Linett", "Liza", "Lora", "Lotti", "Luca", "Lujza", "László", "Léna", "Lívia", "Maja", "Marcell", "Martin", "Mia", "Mihály", "Miklós", "Milla", "Milán", "Mira", "Mirella", "Mirkó", "Márk", "Márton", "Mátyás", "Máté", "Nara", "Natasa", "Natália", "Nikolasz", "Nimród", "Nina", "Noel", "Nolen", "Norbert", "Norina", "Noé", "Noémi", "Nándor", "Nátán", "Nóra", "Olivér", "Olívia", "Panka", "Panna", "Patrik", "Petra", "Péter", "Rebeka", "Regina", "Richárd", "Roland", "Rozina", "Réka", "Róbert", "Róza", "Simon", "Soma", "Szabolcs", "Szofi", "Szofia", "Szonja", "Szófia", "Sámuel", "Sándor", "Sára", "Tamara", "Tamás", "Tibor", "Vanda", "Vencel", "Vendel", "Veronika", "Viktor", "Viktória", "Vilmos", "Vince", "Virág", "Vivien", "Zalán", "Zara", "Zejnep", "Zente", "Zita", "Zoltán", "Zorka", "Zoé", "Zselyke", "Zsolt", "Zsombor", "Zsófia", "Zénó", "Zétény", "Ábel", "Ádám", "Ákos", "Ármin", "Áron" };

pub const last_name = [_][]const u8{ "Nagy", "Kovács", "Tóth", "Szabó", "Horváth", "Varga", "Kiss", "Molnár", "Németh", "Farkas", "Balogh", "Papp", "Takács", "Juhász", "Lakatos", "Mészáros", "Oláh", "Simon", "Rácz", "Fekete", "Szilágyi", "Török", "Fehér", "Balázs", "Gál", "Kis", "Szűcs", "Kocsis", "Orsós", "Pintér", "Fodor", "Szalai", "Sipos", "Magyar", "Lukács", "Gulyás", "Biró", "Király", "László", "Katona", "Jakab", "Bogdán", "Balog", "Sándor", "Boros", "Fazekas", "Kelemen", "Váradi", "Antal", "Somogyi", "Orosz", "Fülöp", "Veres", "Vincze", "Hegedűs", "Budai", "Deák", "Pap", "Bálint", "Pál", "Illés", "Vass", "Szőke", "Vörös", "Bognár", "Fábián", "Lengyel", "Bodnár", "Szücs", "Hajdu", "Halász", "Jónás", "Máté", "Székely", "Kozma", "Gáspár", "Pásztor", "Bakos", "Dudás", "Major", "Orbán", "Hegedüs", "Virág", "Barna", "Novák", "Soós", "Tamás", "Nemes", "Pataki", "Balla", "Faragó", "Kerekes", "Borbély", "Barta", "Péter", "Szekeres", "Csonka", "Mezei", "Márton", "Sárközi" };

pub const last_name_pattern = [_]NamePattern{.{ .value = "{{person.last_name}}", .weight = 1 }};

pub const male_first_name = [_][]const u8{ "Bence", "Máté", "Dominik", "Levente", "Noel", "Dániel", "Zalán", "Marcell", "Olivér", "Ádám", "Milán", "Dávid", "Botond", "Benett", "Áron", "Zsombor", "Balázs", "Márk", "Péter", "Kristóf", "Zétény", "Nimród", "László", "Benedek", "Tamás", "Gergő", "Patrik", "Zente", "Bálint", "András", "Zoltán", "Attila", "Barnabás", "Márton", "Hunor", "Kornél", "Martin", "Ákos", "Gábor", "Alex", "István", "Vince", "Ábel", "Krisztián", "Zsolt", "János", "Nolen", "Erik", "Bendegúz", "Sándor", "József", "Nándor", "Richárd", "Benjámin", "Soma", "Ármin", "Csaba", "Kevin", "Róbert", "Ferenc", "Mátyás", "Norbert", "Roland", "Vencel", "Viktor", "Csongor", "Szabolcs", "Mihály", "Boldizsár", "Benjamin", "Simon", "Gergely", "Bertalan", "Tibor", "Zénó", "Adrián", "Miklós", "Nikolasz", "Vilmos", "Kende", "Imre", "Gellért", "Krisztofer", "Donát", "Vendel", "Bende", "Brájen", "Dorián", "Denisz", "Sámuel", "Noé", "Csanád", "Lajos", "Kolos", "Alexander", "Laurent", "Mirkó", "György", "Nátán", "Iván" };

pub const male_prefix = [_][]const u8{ "Dr.", "Prof." };

pub const name = [_]NamePattern{ .{ .value = "{{person.prefix}} {{person.lastName}} {{person.firstName}}", .weight = 1 }, .{ .value = "{{person.lastName}} {{person.firstName}}", .weight = 9 } };

pub const prefix = [_][]const u8{ "Dr.", "Prof." };
