const NamePattern = @import("../../modules/person.zig").NamePattern;

pub const female_first_name = [_][]const u8{ "Emma", "Louise", "Marie", "Elise", "Noor", "Ella", "Julie", "Lotte", "Lore", "Fien", "Lena", "Mila", "Olivia", "Amber", "Anna", "Elena", "Hanne", "Laura", "Charlotte", "Lina", "Nina", "Fleur", "Lisa", "Nora", "Juliette", "Luna", "Amelie", "Kato", "Sara", "Febe", "Axelle", "Janne", "Eline", "Helena", "Noa", "Camille", "Roos", "Lily", "Jade", "Nore", "Jana", "Manon", "Sarah", "Liv", "Amélie", "Lara", "Mona", "Alice", "Tess", "Kaat", "Femke", "Aya", "Eva", "Lien", "Bo", "Zoe", "Oona", "Sofia", "Leonie", "Linde", "Jolien", "Fran", "Pauline", "Laure", "Merel", "Marthe", "Yana", "Renée", "Paulien", "Margot", "Yasmine", "Ines", "Elisa", "Emily", "Maya", "Floor", "Amy", "Lize", "Amina", "Lucie", "Julia", "Lise", "Hailey", "Hannah", "Alicia", "Norah", "Margaux", "Lieze", "Sien", "Zoë", "Inaya", "Aline", "Amira", "Victoria", "Flore", "Lana", "Sterre", "Maud", "Chloe" };

pub const female_prefix = [_][]const u8{ "Dr.", "Ir.", "Ing.", "Prof." };

pub const first_name = [_][]const u8{ "Aaron", "Adam", "Alex", "Alexander", "Alice", "Alicia", "Aline", "Amber", "Amelie", "Amina", "Amira", "Amy", "Amélie", "Anna", "Arne", "Arthur", "Axel", "Axelle", "Aya", "Bas", "Bent", "Bo", "Bram", "Brent", "Camille", "Cas", "Charlotte", "Chloe", "Daan", "David", "Dries", "Elena", "Elias", "Eline", "Elisa", "Elise", "Ella", "Emiel", "Emile", "Emily", "Emma", "Eva", "Febe", "Felix", "Femke", "Ferre", "Fien", "Finn", "Fleur", "Floor", "Flore", "Fran", "Gabriel", "Gilles", "Gust", "Hailey", "Hamza", "Hannah", "Hanne", "Helena", "Ilias", "Ilyas", "Imran", "Inaya", "Ines", "Jack", "Jade", "Jana", "Janne", "Jarne", "Jasper", "Jayden", "Jef", "Jelle", "Jens", "Jesse", "Jolien", "Jonas", "Jules", "Julia", "Julie", "Juliette", "Juul", "Kaat", "Kasper", "Kato", "Kobe", "Lana", "Lander", "Lara", "Lars", "Laura", "Laure", "Lena", "Lenn", "Lennert", "Leon", "Leonie", "Lewis", "Liam", "Lien", "Lieze", "Lily", "Lina", "Linde", "Lisa", "Lise", "Liv", "Lize", "Lore", "Lotte", "Lou", "Louis", "Louise", "Lowie", "Luca", "Lucas", "Lucie", "Lukas", "Luna", "Manon", "Margaux", "Margot", "Marie", "Marthe", "Mathias", "Mathis", "Mats", "Matteo", "Matthias", "Maud", "Maurice", "Mauro", "Maxim", "Maxime", "Maya", "Merel", "Miel", "Mila", "Milan", "Milo", "Mohamed", "Mona", "Nand", "Nathan", "Nicolas", "Niels", "Nina", "Noa", "Noah", "Noor", "Nora", "Norah", "Nore", "Olivia", "Oona", "Oscar", "Paulien", "Pauline", "Quinten", "Rayan", "Renée", "Robbe", "Robin", "Roos", "Ruben", "Rune", "Sam", "Sander", "Sara", "Sarah", "Sem", "Senne", "Seppe", "Siebe", "Sien", "Simon", "Sofia", "Stan", "Sterre", "Tess", "Thibo", "Thomas", "Tibo", "Tristan", "Tuur", "Vic", "Victor", "Victoria", "Viktor", "Vince", "Wannes", "Warre", "Wout", "Xander", "Yana", "Yasmine", "Zoe", "Zoë" };

pub const last_name = [_][]const u8{ "Claes", "Claeys", "Declerck", "Declercq", "Decock", "Decoster", "Desmet", "Devos", "Dewilde", "Gielen", "Goossens", "Hermans", "Jacobs", "Janssen", "Janssens", "Lemmens", "Maes", "Martens", "Mertens", "Michiels", "Peeters", "Smet", "Smets", "Thijs", "Vandamme", "Vandenberghe", "Vandenbroeck", "Vandevelde", "Verhaeghe", "Verstraete", "Willems", "Wouters" };

pub const last_name_pattern = [_]NamePattern{.{ .value = "{{person.last_name}}", .weight = 1 }};

pub const male_first_name = [_][]const u8{ "Lucas", "Liam", "Louis", "Noah", "Lars", "Arthur", "Mathis", "Kobe", "Wout", "Milan", "Alexander", "Daan", "Adam", "Vince", "Jules", "Victor", "Finn", "Stan", "Leon", "Seppe", "Senne", "Thomas", "Mats", "Robbe", "Matteo", "Ferre", "Nathan", "Warre", "Jasper", "Vic", "Elias", "Tuur", "Lowie", "Mauro", "Maxim", "Ruben", "Rune", "Mohamed", "Simon", "Rayan", "Lukas", "Lander", "Xander", "Emiel", "Siebe", "Jonas", "Sam", "Luca", "Arne", "Cas", "Felix", "Jack", "Mathias", "Jayden", "Quinten", "Tibo", "Lewis", "Sem", "Maxime", "Viktor", "Emile", "Sander", "Aaron", "Oscar", "Bas", "Niels", "Jef", "Nand", "Lou", "Tristan", "Gust", "David", "Brent", "Jelle", "Lenn", "Miel", "Wannes", "Gilles", "Jarne", "Alex", "Imran", "Lennert", "Milo", "Jens", "Matthias", "Dries", "Axel", "Juul", "Hamza", "Ilias", "Thibo", "Nicolas", "Bent", "Jesse", "Bram", "Maurice", "Ilyas", "Gabriel", "Robin", "Kasper" };

pub const male_prefix = [_][]const u8{ "Dr.", "Ir.", "Ing.", "Prof." };

pub const name = [_]NamePattern{ .{ .value = "{{person.prefix}} {{person.firstName}} {{person.lastName}}", .weight = 1 }, .{ .value = "{{person.firstName}} {{person.lastName}} {{person.suffix}}", .weight = 1 }, .{ .value = "{{person.firstName}} {{person.lastName}}", .weight = 8 } };

pub const prefix = [_][]const u8{ "Dr.", "Ing.", "Ir.", "Prof." };

pub const suffix = [_][]const u8{ "MBA", "Phd." };
