const Currency = @import("../../modules/finance.zig").Currency;

pub const account_type = [_][]const u8{ "پس انداز", "سرمایه گذاری", "وام مسکن", "کارت اعتباری", "وام خودرو", "وام شخصی" };

pub const credit_card = .{ .mastercard = [_][]const u8{ "5[1-5]##-####-####-###L", "6771-89##-####-###L" }, .visa = [_][]const u8{ "4###########L", "4###-####-####-###L" } };

pub const currency = [_]Currency{ .{ .name = "درهم امارات", .code = "AED", .symbol = "" }, .{ .name = "افغانی", .code = "AFN", .symbol = "؋" }, .{ .name = "پزو آرژانتین", .code = "ARS", .symbol = "$" }, .{ .name = "دلار استرالیا", .code = "AUD", .symbol = "$" }, .{ .name = "مانات آذربایجان", .code = "AZN", .symbol = "ман" }, .{ .name = "دلار کانادا", .code = "CAD", .symbol = "$" }, .{ .name = "فرانک سوئیس", .code = "CHF", .symbol = "CHF" }, .{ .name = "کرون چک", .code = "CZK", .symbol = "Kč" }, .{ .name = "کرون", .code = "EEK", .symbol = "" }, .{ .name = "دینار عراق", .code = "IQD", .symbol = "" }, .{ .name = "ریال ایران", .code = "IRR", .symbol = "﷼" }, .{ .name = "کرون ایسلند", .code = "ISK", .symbol = "kr" }, .{ .name = "دینار اردن", .code = "JOD", .symbol = "" }, .{ .name = "ین", .code = "JPY", .symbol = "¥" }, .{ .name = "دینار کویت", .code = "KWD", .symbol = "" }, .{ .name = "دینار لیبی", .code = "LYD", .symbol = "" }, .{ .name = "درهم مراکش", .code = "MAD", .symbol = "" }, .{ .name = "روپی نپال", .code = "NPR", .symbol = "₨" }, .{ .name = "ریال عمان", .code = "OMR", .symbol = "﷼" }, .{ .name = "پزو فیلیپین", .code = "PHP", .symbol = "Php" }, .{ .name = "روپی پاکستان", .code = "PKR", .symbol = "₨" }, .{ .name = "ریال قطر", .code = "QAR", .symbol = "﷼" }, .{ .name = "روبل روسیه", .code = "RUB", .symbol = "руб" }, .{ .name = "ریال عربستان", .code = "SAR", .symbol = "﷼" }, .{ .name = "پوند سودان", .code = "SDG", .symbol = "" }, .{ .name = "کرون سوئد", .code = "SEK", .symbol = "kr" }, .{ .name = "دلار سنگاپور", .code = "SGD", .symbol = "$" } };

pub const transaction_type = [_][]const u8{ "سپرده", "برداشت از حساب", "پرداخت", "صورتحساب" };
