pub const building_number = [_][]const u8{ " s/n.", ", #", ", ##", " #", " ##" };

pub const city_name = [_][]const u8{ "Parla", "Telde", "Baracaldo", "San Fernando", "Torrevieja", "Lugo", "Santiago de Compostela", "Gerona", "Cáceres", "Lorca", "Coslada", "Talavera de la Reina", "El Puerto de Santa María", "Cornellá de Llobregat", "Avilés", "Palencia", "Gecho", "Orihuela", "Pontevedra", "Pozuelo de Alarcón", "Toledo", "El Ejido", "Guadalajara", "Gandía", "Ceuta", "Ferrol", "Chiclana de la Frontera", "Manresa", "Roquetas de Mar", "Ciudad Real", "Rubí", "Benidorm", "San Sebastían de los Reyes", "Ponferrada", "Zamora", "Alcalá de Guadaira", "Fuengirola", "Mijas", "Sanlúcar de Barrameda", "La Línea de la Concepción", "Majadahonda", "Sagunto", "El Prat de LLobregat", "Viladecans", "Linares", "Alcoy", "Irún", "Estepona", "Torremolinos", "Rivas-Vaciamadrid", "Molina de Segura", "Paterna", "Granollers", "Santa Lucía de Tirajana", "Motril", "Cerdañola del Vallés", "Arrecife", "Segovia", "Torrelavega", "Elda", "Mérida", "Ávila", "Valdemoro", "Cuenta", "Collado Villalba", "Benalmádena", "Mollet del Vallés", "Puertollano", "Madrid", "Barcelona", "Valencia", "Sevilla", "Zaragoza", "Málaga", "Murcia", "Palma de Mallorca", "Las Palmas de Gran Canaria", "Bilbao", "Córdoba", "Alicante", "Valladolid", "Vigo", "Gijón", "Hospitalet de LLobregat", "La Coruña", "Granada", "Vitoria", "Elche", "Santa Cruz de Tenerife", "Oviedo", "Badalona", "Cartagena", "Móstoles", "Jerez de la Frontera", "Tarrasa", "Sabadell", "Alcalá de Henares", "Pamplona", "Fuenlabrada", "Almería", "San Sebastián", "Leganés", "Santander", "Burgos", "Castellón de la Plana", "Alcorcón", "Albacete", "Getafe", "Salamanca", "Huelva", "Logroño", "Badajoz", "San Cristróbal de la Laguna", "León", "Tarragona", "Cádiz", "Lérida", "Marbella", "Mataró", "Dos Hermanas", "Santa Coloma de Gramanet", "Jaén", "Algeciras", "Torrejón de Ardoz", "Orense", "Alcobendas", "Reus", "Calahorra", "Inca", "Aýna" };

pub const city_pattern = [_][]const u8{"{{location.city_name}}"};

pub const country = [_][]const u8{ "Afganistán", "Albania", "Argelia", "Andorra", "Angola", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbayán", "Bahamas", "Barein", "Bangladesh", "Barbados", "Bielorusia", "Bélgica", "Belice", "Bermuda", "Bután", "Bolivia", "Bosnia Herzegovina", "Botswana", "Brasil", "Bulgaria", "Burkina Faso", "Burundi", "Camboya", "Camerún", "Canada", "Cabo Verde", "Islas Caimán", "Chad", "Chile", "China", "Isla de Navidad", "Colombia", "Comodos", "Congo", "Costa Rica", "Costa de Marfil", "Croacia", "Cuba", "Chipre", "República Checa", "Dinamarca", "Dominica", "República Dominicana", "Ecuador", "Egipto", "El Salvador", "Guinea Ecuatorial", "Eritrea", "Estonia", "Etiopía", "Islas Faro", "Fiji", "Finlandia", "Francia", "Gabón", "Gambia", "Georgia", "Alemania", "Ghana", "Grecia", "Groenlandia", "Granada", "Guadalupe", "Guam", "Guatemala", "Guinea", "Guinea-Bisau", "Guayana", "Haiti", "Honduras", "Hong Kong", "Hungria", "Islandia", "India", "Indonesia", "Iran", "Irak", "Irlanda", "Italia", "Jamaica", "Japón", "Jordania", "Kazajistan", "Kenia", "Kiribati", "Corea", "Kuwait", "Letonia", "Líbano", "Liberia", "Liechtenstein", "Lituania", "Luxemburgo", "Macao", "Macedonia", "Madagascar", "Malawi", "Malasia", "Maldivas", "Mali", "Malta", "Martinica", "Mauritania", "Méjico", "Micronesia", "Moldavia", "Mónaco", "Mongolia", "Montenegro", "Montserrat", "Marruecos", "Mozambique", "Namibia", "Nauru", "Nepal", "Países Bajos", "Nueva Zelanda", "Nicaragua", "Niger", "Nigeria", "Noruega", "Omán", "Pakistan", "Panamá", "Papúa Nueva Guinea", "Paraguay", "Perú", "Filipinas", "Poland", "Portugal", "Puerto Rico", "Rusia", "Ruanda", "Samoa", "San Marino", "Santo Tomé y Principe", "Arabia Saudí", "Senegal", "Serbia", "Seychelles", "Sierra Leona", "Singapur", "Eslovaquia", "Eslovenia", "Somalia", "España", "Sri Lanka", "Sudán", "Suriname", "Suecia", "Suiza", "Siria", "Taiwan", "Tajikistan", "Tanzania", "Tailandia", "Timor-Leste", "Togo", "Tonga", "Trinidad y Tobago", "Tunez", "Turquia", "Uganda", "Ucrania", "Emiratos Árabes Unidos", "Reino Unido", "Estados Unidos de América", "Uruguay", "Uzbekistan", "Vanuatu", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe" };

pub const county = [_][]const u8{ "Álava", "Albacete", "Alicante", "Almería", "Asturias", "Ávila", "Badajoz", "Barcelona", "Burgos", "Cantabria", "Castellón", "Ciudad Real", "Cuenca", "Cáceres", "Cádiz", "Córdoba", "Gerona", "Granada", "Guadalajara", "Guipúzcoa", "Huelva", "Huesca", "Islas Baleares", "Jaén", "La Coruña", "La Rioja", "Las Palmas", "León", "Lugo", "lérida", "Madrid", "Murcia", "Málaga", "Navarra", "Orense", "Palencia", "Pontevedra", "Salamanca", "Santa Cruz de Tenerife", "Segovia", "Sevilla", "Soria", "Tarragona", "Teruel", "Toledo", "Valencia", "Valladolid", "Vizcaya", "Zamora", "Zaragoza" };

pub const default_country = [_][]const u8{"España"};

pub const postcode = [_][]const u8{"#####"};

pub const secondary_address = [_][]const u8{ "Esc. ###", "Puerta ###" };

pub const state = [_][]const u8{ "Andalucía", "Aragón", "Principado de Asturias", "Baleares", "Canarias", "Cantabria", "Castilla-La Mancha", "Castilla y León", "Cataluña", "Comunidad Valenciana", "Extremadura", "Galicia", "La Rioja", "Comunidad de Madrid", "Navarra", "País Vasco", "Región de Murcia" };

pub const state_abbr = [_][]const u8{ "And", "Ara", "Ast", "Bal", "Can", "Cbr", "Man", "Leo", "Cat", "Com", "Ext", "Gal", "Rio", "Mad", "Nav", "Vas", "Mur" };

pub const street_address = .{ .normal = "{{location.street}}{{location.buildingNumber}}", .full = "{{location.street}}{{location.buildingNumber}} {{location.secondaryAddress}}" };

pub const street_pattern = [_][]const u8{ "{{location.street_suffix}} {{person.first_name}}", "{{location.street_suffix}} {{person.first_name}} {{person.last_name}}" };

pub const street_suffix = [_][]const u8{ "Aldea", "Apartamento", "Arrabal", "Arroyo", "Avenida", "Bajada", "Barranco", "Barrio", "Bloque", "Calle", "Calleja", "Camino", "Carretera", "Caserio", "Colegio", "Colonia", "Conjunto", "Cuesta", "Chalet", "Edificio", "Entrada", "Escalinata", "Explanada", "Extramuros", "Extrarradio", "Ferrocarril", "Glorieta", "Gran Subida", "Grupo", "Huerta", "Jardines", "Lado", "Lugar", "Manzana", "Masía", "Mercado", "Monte", "Muelle", "Municipio", "Parcela", "Parque", "Partida", "Pasaje", "Paseo", "Plaza", "Poblado", "Polígono", "Prolongación", "Puente", "Puerta", "Quinta", "Ramal", "Rambla", "Rampa", "Riera", "Rincón", "Ronda", "Rua", "Salida", "Sector", "Sección", "Senda", "Solar", "Subida", "Terrenos", "Torrente", "Travesía", "Urbanización", "Vía", "Vía Pública" };
