const NamePattern = @import("../../modules/person.zig").NamePattern;

pub const female_first_name = [_][]const u8{ "Anna", "Eva", "Maria", "Karin", "Sara", "Kristina", "Lena", "Emma", "Kerstin", "Marie", "Malin", "Ingrid", "Jenny", "Hanna", "Linda", "Annika", "Susanne", "Elin", "Monica", "Birgitta", "Sofia", "Johanna", "Inger", "Carina", "Elisabeth", "Julia", "Ulla", "Katarina", "Linnéa", "Emelie", "Ida", "Helena", "Camilla", "Åsa", "Anette", "Sandra", "Gunilla", "Anita", "Maja", "Marianne", "Margareta", "Amanda", "Anneli", "Therese", "Ann", "Josefin", "Cecilia", "Jessica", "Helen", "Lisa", "Matilda", "Caroline", "Alice", "Frida", "Ulrika", "Elsa", "Barbro", "Siv", "Rebecca", "Madeleine", "Klara", "Ebba", "Sofie", "Isabelle", "Agneta", "Gun", "Wilma", "Lina", "Berit", "Pia", "Ella", "Ellen", "Yvonne", "Louise", "Astrid", "Moa", "Olivia", "Nathalie", "Mona", "Agnes", "Emilia", "Alexandra", "Alva", "Britt", "Erika", "Viktoria", "Ann-Christin", "Felicia", "Ann-Marie", "Sonja", "Britt-Marie", "Pernilla", "Lovisa", "Charlotte", "Linn", "Gunnel", "Nina", "Mikaela", "Karolina", "Lisbeth" };

pub const female_prefix = [_][]const u8{ "Dr.", "Prof.", "PhD." };

pub const first_name = [_][]const u8{ "Anna", "Eva", "Maria", "Karin", "Sara", "Kristina", "Lena", "Emma", "Kerstin", "Marie", "Malin", "Ingrid", "Jenny", "Hanna", "Linda", "Annika", "Susanne", "Elin", "Monica", "Birgitta", "Sofia", "Johanna", "Inger", "Carina", "Elisabeth", "Julia", "Ulla", "Katarina", "Linnéa", "Emelie", "Ida", "Helena", "Camilla", "Åsa", "Anette", "Sandra", "Gunilla", "Anita", "Maja", "Marianne", "Margareta", "Amanda", "Anneli", "Therese", "Ann", "Josefin", "Cecilia", "Jessica", "Helen", "Lisa", "Matilda", "Caroline", "Alice", "Frida", "Ulrika", "Elsa", "Barbro", "Siv", "Rebecca", "Madeleine", "Klara", "Ebba", "Sofie", "Isabelle", "Agneta", "Gun", "Wilma", "Lina", "Berit", "Pia", "Ella", "Ellen", "Yvonne", "Louise", "Astrid", "Moa", "Olivia", "Nathalie", "Mona", "Agnes", "Emilia", "Alexandra", "Alva", "Britt", "Erika", "Viktoria", "Ann-Christin", "Felicia", "Ann-Marie", "Sonja", "Britt-Marie", "Pernilla", "Lovisa", "Charlotte", "Linn", "Gunnel", "Nina", "Mikaela", "Karolina", "Lisbeth", "Lars", "Mikael", "Anders", "Johan", "Erik", "Per", "Peter", "Karl", "Thomas", "Jan", "Daniel", "Fredrik", "Andreas", "Hans", "Stefan", "Mohamed", "Mats", "Marcus", "Mattias", "Magnus", "Jonas", "Oskar", "Alexander", "Niklas", "Bengt", "Martin", "Bo", "Nils", "Viktor", "Patrik", "Björn", "David", "Leif", "Filip", "Henrik", "Joakim", "Emil", "Christer", "Ulf", "Sven", "Simon", "Christoffer", "Anton", "Gustav", "Robert", "Christian", "William", "Tommy", "Kjell", "Lucas", "Rickard", "Håkan", "Adam", "Göran", "Jakob", "Jonathan", "Rolf", "Lennart", "Robin", "Sebastian", "Elias", "Tobias", "John", "Stig", "Axel", "Linus", "Oliver", "Kent", "Hugo", "Isak", "Roger", "Jesper", "Claes", "Albin", "Ludvig", "Jörgen", "Rasmus", "Max", "Ali", "Jimmy", "Kenneth", "Joel", "Gunnar", "Dennis", "Josef", "Johnny", "Olle", "Liam", "Leo", "Olof", "Pontus", "Åke", "Kurt", "Kevin", "Samuel", "Edvin", "Gabriel", "Torbjörn", "Arvid", "Felix" };

pub const last_name = [_][]const u8{ "Andersson", "Johansson", "Karlsson", "Nilsson", "Eriksson", "Larsson", "Olsson", "Persson", "Svensson", "Gustafsson", "Pettersson", "Jonsson", "Jansson", "Hansson", "Bengtsson", "Jönsson", "Lindberg", "Jakobsson", "Magnusson", "Olofsson", "Lindström", "Lindqvist", "Lindgren", "Berg", "Axelsson", "Bergström", "Lundberg", "Lind", "Lundgren", "Lundqvist", "Mattsson", "Berglund", "Fredriksson", "Sandberg", "Henriksson", "Forsberg", "Sjöberg", "Ali", "Wallin", "Mohamed", "Engström", "Eklund", "Danielsson", "Lundin", "Håkansson", "Björk", "Bergman", "Gunnarsson", "Holm", "Wikström", "Samuelsson", "Isaksson", "Fransson", "Bergqvist", "Nyström", "Holmberg", "Arvidsson", "Löfgren", "Söderberg", "Nyberg", "Blomqvist", "Claesson", "Nordström", "Ahmed", "Mårtensson", "Lundström", "Hassan", "Viklund", "Björklund", "Eliasson", "Pålsson", "Berggren", "Sandström", "Lund", "Nordin", "Ström", "Åberg", "Falk", "Ekström", "Hermansson", "Holmgren", "Hellström", "Dahlberg", "Hedlund", "Sundberg", "Sjögren", "Ek", "Blom", "Abrahamsson", "Martinsson", "Öberg", "Andreasson", "Strömberg", "Månsson", "Hansen", "Åkesson", "Dahl", "Lindholm", "Norberg", "Holmqvist" };

pub const last_name_pattern = [_]NamePattern{ .{ .value = "{{person.last_name}}", .weight = 8 }, .{ .value = "{{person.last_name}} {{person.last_name}}", .weight = 2 } };

pub const male_first_name = [_][]const u8{ "Lars", "Mikael", "Anders", "Johan", "Erik", "Per", "Peter", "Karl", "Thomas", "Jan", "Daniel", "Fredrik", "Andreas", "Hans", "Stefan", "Mohamed", "Mats", "Marcus", "Mattias", "Magnus", "Jonas", "Oskar", "Alexander", "Niklas", "Bengt", "Martin", "Bo", "Nils", "Viktor", "Patrik", "Björn", "David", "Leif", "Filip", "Henrik", "Joakim", "Emil", "Christer", "Ulf", "Sven", "Simon", "Christoffer", "Anton", "Gustav", "Robert", "Christian", "William", "Tommy", "Kjell", "Lucas", "Rickard", "Håkan", "Adam", "Göran", "Jakob", "Jonathan", "Rolf", "Lennart", "Robin", "Sebastian", "Elias", "Tobias", "John", "Stig", "Axel", "Linus", "Oliver", "Kent", "Hugo", "Isak", "Roger", "Jesper", "Claes", "Albin", "Ludvig", "Jörgen", "Rasmus", "Max", "Ali", "Jimmy", "Kenneth", "Joel", "Gunnar", "Dennis", "Josef", "Johnny", "Olle", "Liam", "Leo", "Olof", "Pontus", "Åke", "Kurt", "Kevin", "Samuel", "Edvin", "Gabriel", "Torbjörn", "Arvid", "Felix" };

pub const male_prefix = [_][]const u8{ "Dr.", "Prof.", "PhD." };

pub const name = [_]NamePattern{ .{ .value = "{{person.prefix}} {{person.firstName}} {{person.lastName}}", .weight = 1 }, .{ .value = "{{person.firstName}} {{person.lastName}} {{person.suffix}}", .weight = 1 }, .{ .value = "{{person.firstName}} {{person.lastName}}", .weight = 9 } };

pub const prefix = [_][]const u8{ "Dr.", "PhD.", "Prof." };

pub const title = .{ .descriptor = [_][]const u8{ "Ansvarig", "Senior", "Junior", "Företags", "Organisatorisk", "Intern", "Tillträdande", "Nationell", "Internationell", "Regional", "Global" }, .level = [_][]const u8{ "Verkställande", "Program", "Varumärke", "Säkerhet", "Forskning", "Marknadsföring", "Direktiv", "Implementation", "Integration", "Funktionalitet", "Taktik", "Marknader", "Division", "Grupp", "Optimering", "Infrastruktur", "Operativ", "Finansiell", "Kommunikation" }, .job = [_][]const u8{ "Direktör", "Ingenjör", "Handledare", "Koordinator", "Specialist", "Administratör", "Arkitekt", "Analytiker", "Designer", "Planerare", "Tekniker", "Utvecklare", "Konsult", "Representant", "Chef", "Producent", "Assistent" } };
