const NamePattern = @import("../../modules/person.zig").NamePattern;

pub const female_first_name = [_][]const u8{ "Alessandra", "Alice", "Aline", "Alícia", "Ana Clara", "Ana Júlia", "Ana Laura", "Ana Luiza", "Antonella", "Beatriz", "Bruna", "Carla", "Cecília", "Clara", "Célia", "Dalila", "Eduarda", "Elisa", "Eloá", "Emanuelly", "Esther", "Fabrícia", "Felícia", "Giovanna", "Helena", "Heloísa", "Isabel", "Isabela", "Isabella", "Isabelly", "Isis", "Janaína", "Joana", "Júlia", "Karla", "Lara", "Larissa", "Laura", "Lavínia", "Liz", "Lorena", "Lorraine", "Luiza", "Lívia", "Maitê", "Manuela", "Marcela", "Margarida", "Maria", "Maria Alice", "Maria Cecília", "Maria Clara", "Maria Eduarda", "Maria Helena", "Maria Júlia", "Maria Luiza", "Mariana", "Marina", "Marli", "Meire", "Melissa", "Morgana", "Márcia", "Mércia", "Natália", "Núbia", "Ofélia", "Paula", "Rafaela", "Rebeca", "Roberta", "Sara", "Sarah", "Sophia", "Suélen", "Sílvia", "Talita", "Valentina", "Vitória", "Yasmin" };

pub const female_prefix = [_][]const u8{ "Sra.", "Srta.", "Dra." };

pub const first_name = [_][]const u8{ "Alessandra", "Alessandro", "Alexandre", "Alice", "Aline", "Alícia", "Ana Clara", "Ana Júlia", "Ana Laura", "Ana Luiza", "Anthony", "Antonella", "Antônio", "Arthur", "Beatriz", "Benjamin", "Benício", "Bernardo", "Breno", "Bruna", "Bryan", "Caio", "Calebe", "Carla", "Carlos", "Cauã", "Cecília", "Clara", "Célia", "César", "Dalila", "Daniel", "Danilo", "Davi", "Davi Lucca", "Deneval", "Eduarda", "Eduardo", "Elisa", "Eloá", "Elísio", "Emanuel", "Emanuelly", "Enzo", "Enzo Gabriel", "Esther", "Fabiano", "Fabrícia", "Fabrício", "Feliciano", "Felipe", "Felícia", "Frederico", "Fábio", "Félix", "Gabriel", "Gael", "Giovanna", "Guilherme", "Gustavo", "Gúbio", "Heitor", "Helena", "Heloísa", "Henrique", "Hugo", "Hélio", "Isaac", "Isabel", "Isabela", "Isabella", "Isabelly", "Isadora", "Isis", "Janaína", "Joana", "Joaquim", "João", "João Lucas", "João Miguel", "João Pedro", "Júlia", "Júlio", "Júlio César", "Karla", "Kléber", "Ladislau", "Lara", "Larissa", "Laura", "Lavínia", "Leonardo", "Liz", "Lorena", "Lorenzo", "Lorraine", "Lucas", "Lucca", "Luiza", "Lívia", "Maitê", "Manuela", "Marcela", "Marcelo", "Marcos", "Margarida", "Maria", "Maria Alice", "Maria Cecília", "Maria Clara", "Maria Eduarda", "Maria Helena", "Maria Júlia", "Maria Luiza", "Mariana", "Marina", "Marli", "Matheus", "Meire", "Melissa", "Miguel", "Morgana", "Murilo", "Márcia", "Mércia", "Nataniel", "Natália", "Nicolas", "Noah", "Norberto", "Núbia", "Ofélia", "Pablo", "Paula", "Paulo", "Pedro", "Pedro Henrique", "Pietro", "Rafael", "Rafaela", "Raul", "Rebeca", "Ricardo", "Roberta", "Roberto", "Salvador", "Samuel", "Sara", "Sarah", "Silas", "Sirineu", "Sophia", "Suélen", "Sílvia", "Talita", "Tertuliano", "Théo", "Valentina", "Vicente", "Vitor", "Vitória", "Víctor", "Warley", "Washington", "Yago", "Yango", "Yasmin", "Yuri", "Ígor" };

pub const last_name = [_][]const u8{ "Silva", "Souza", "Carvalho", "Santos", "Reis", "Xavier", "Franco", "Braga", "Macedo", "Batista", "Barros", "Moraes", "Costa", "Pereira", "Melo", "Saraiva", "Nogueira", "Oliveira", "Martins", "Moreira", "Albuquerque" };

pub const last_name_pattern = [_]NamePattern{.{ .value = "{{person.last_name}}", .weight = 1 }};

pub const male_first_name = [_][]const u8{ "Alessandro", "Alexandre", "Anthony", "Antônio", "Arthur", "Benjamin", "Benício", "Bernardo", "Breno", "Bryan", "Caio", "Calebe", "Carlos", "Cauã", "César", "Daniel", "Danilo", "Davi", "Davi Lucca", "Deneval", "Eduardo", "Elísio", "Emanuel", "Enzo", "Enzo Gabriel", "Fabiano", "Fabrício", "Feliciano", "Felipe", "Frederico", "Fábio", "Félix", "Gabriel", "Gael", "Guilherme", "Gustavo", "Gúbio", "Heitor", "Henrique", "Hugo", "Hélio", "Isaac", "Joaquim", "João", "João Lucas", "João Miguel", "João Pedro", "Júlio", "Júlio César", "Kléber", "Ladislau", "Leonardo", "Lorenzo", "Lucas", "Lucca", "Marcelo", "Marcos", "Matheus", "Miguel", "Murilo", "Nataniel", "Nicolas", "Noah", "Norberto", "Pablo", "Paulo", "Pedro", "Pedro Henrique", "Pietro", "Rafael", "Raul", "Ricardo", "Roberto", "Salvador", "Samuel", "Silas", "Sirineu", "Tertuliano", "Théo", "Vicente", "Vitor", "Víctor", "Warley", "Washington", "Yago", "Yango", "Yuri", "Ígor" };

pub const male_prefix = [_][]const u8{ "Sr.", "Dr." };

pub const name = [_]NamePattern{ .{ .value = "{{person.prefix}} {{person.firstName}} {{person.lastName}}", .weight = 1 }, .{ .value = "{{person.firstName}} {{person.lastName}} {{person.suffix}}", .weight = 1 }, .{ .value = "{{person.firstName}} {{person.lastName}}", .weight = 8 } };

pub const prefix = [_][]const u8{ "Dr.", "Dra.", "Sr.", "Sra.", "Srta." };

pub const sex = [_][]const u8{ "Feminino", "Masculino" };

pub const suffix = [_][]const u8{ "Jr.", "Neto", "Filho" };

pub const title = .{ .descriptor = [_][]const u8{ "Líder", "Senior", "Direto", "Corporativo", "Dinâmico", "Futuro", "Produto", "Nacional", "Regional", "Distrito", "Central", "Global", "Cliente", "Investidor", "International", "Legado", "Avançar", "Interno", "Humano", "Chefe", "Principal" }, .level = [_][]const u8{ "Soluções", "Programa", "Marca", "Segurança", "Pesquisar", "Marketing", "Diretivas", "Implementation", "Implementação", "Funcionalidade", "Resposta", "Paradigma", "Táticas", "Identidade", "Mercados", "Grupo", "Divisão", "Aplicações", "Otimização", "Operações", "Infraestrutura", "Intranet", "Comunicações", "Web", "Branding", "Qualidade", "Assurance", "Mobilidade", "Contas", "Dados", "Criativo", "Configuration", "Prestação de contas", "Interações", "Fatores", "Usabilidade", "Métricas" }, .job = [_][]const u8{ "Supervisor", "Associado", "Executivo", "Atentende", "Policial", "Gerente", "Engenheiro", "Especialista", "Diretor", "Coordenador", "Administrador", "Arquiteto", "Analista", "Designer", "Planejador", "Orquestrador", "Técnico", "Desenvolvedor", "Produtor", "Consultor", "Assistente", "Facilitador", "Agente", "Representante", "Estrategista" } };

pub const western_zodiac_sign = [_][]const u8{ "Aquário", "Peixes", "Áries", "Touro", "Gêmeos", "Câncer", "Leão", "Virgem", "Libra", "Escorpião", "Sagitário", "Capricórnio" };
