pub const adjective = [_][]const u8{ "Adaptativo", "Avanzado", "Asimilado", "Automatizado", "Equilibrado", "Centrado en el negocio", "Centralizado", "Clonado", "Compatible", "Configurable", "Multi grupo", "Multi plataforma", "Centrado en el usuario", "Descentralizado", "Digitalizado", "Distribuido", "Diverso", "Reducido", "Mejorado", "Para toda la empresa", "Ergonomico", "Exclusivo", "Expandido", "Extendido", "Cara a cara", "Enfocado", "Totalmente configurable", "Fundamental", "Orígenes", "Horizontal", "Implementado", "Innovador", "Integrado", "Intuitivo", "Inverso", "Gestionado", "Obligatorio", "Monitorizado", "Multi canal", "Multi lateral", "Multi capa", "En red", "Orientado a objetos", "Open-source", "Operativo", "Optimizado", "Opcional", "Organico", "Organizado", "Perseverando", "Persistente", "en fases", "Polarizado", "Pre-emptivo", "Proactivo", "Enfocado a benficios", "Profundo", "Programable", "Progresivo", "Public-key", "Enfocado en la calidad", "Reactivo", "Realineado", "Re-contextualizado", "Re-implementado", "Ingenieria inversa", "Robusto", "Fácil", "Seguro", "Auto proporciona", "Compartible", "Intercambiable", "Sincronizado", "Orientado a equipos", "Total", "Universal", "Actualizable", "Amigable", "Versatil", "Virtual", "Visionario" };

pub const buzz_adjective = [_][]const u8{ "Clics y mortero", "Valor añadido", "Vertical", "Proactivo", "Robusto", "Revolucionario", "Escalable", "De vanguardia", "Innovador", "Intuitivo", "Estratégico", "E-business", "Misión crítica", "Pegajosa", "Doce y cincuenta y nueve de la noche", "24/7", "De extremo a extremo", "Global", "B2B", "B2C", "Granular", "Fricción", "Virtual", "Viral", "Dinámico", "24/365", "Mejor de su clase", "Asesino", "Magnética", "Filo sangriento", "Habilitado web", "Interactiva", "Punto com", "Sexy", "Back-end", "Tiempo real", "Eficiente", "Frontal", "Distribuida", "Sin costura", "Extensible", "Llave en mano", "Clase mundial", "Código abierto", "Multiplataforma", "Cross-media", "Sinérgico", "ladrillos y clics", "Fuera de la caja", "Empresa", "Integrado", "Impactante", "Inalámbrico", "Transparente", "Próxima generación", "User-centric", "Visionario", "A medida", "Ubicua", "Enchufa y juega", "Colaboración", "Convincente", "Holístico", "Ricos" };

pub const buzz_noun = [_][]const u8{ "sinergias", "web-readiness", "paradigmas", "mercados", "asociaciones", "infraestructuras", "plataformas", "iniciativas", "canales", "ojos", "comunidades", "ROI", "soluciones", "minoristas electrónicos", "e-servicios", "elementos de acción", "portales", "nichos", "tecnologías", "contenido", "vortales", "cadenas de suministro", "convergencia", "relaciones", "arquitecturas", "interfaces", "mercados electrónicos", "e-commerce", "sistemas", "ancho de banda", "infomediarios", "modelos", "Mindshare", "entregables", "usuarios", "esquemas", "redes", "aplicaciones", "métricas", "e-business", "funcionalidades", "experiencias", "servicios web", "metodologías" };

pub const buzz_verb = [_][]const u8{ "poner en práctica", "utilizar", "integrar", "racionalizar", "optimizar", "evolucionar", "transformar", "abrazar", "habilitar", "orquestar", "apalancamiento", "reinventar", "agregado", "arquitecto", "mejorar", "incentivar", "transformarse", "empoderar", "Envisioneer", "monetizar", "arnés", "facilitar", "aprovechar", "desintermediar", "sinergia", "estrategias", "desplegar", "marca", "crecer", "objetivo", "sindicato", "sintetizar", "entregue", "malla", "incubar", "enganchar", "maximizar", "punto de referencia", "acelerar", "reintermediate", "pizarra", "visualizar", "reutilizar", "innovar", "escala", "desatar", "conducir", "extender", "ingeniero", "revolucionar", "generar", "explotar", "transición", "e-enable", "repetir", "cultivar", "matriz", "productize", "redefinir", "recontextualizar" };

pub const descriptor = [_][]const u8{ "24 horas", "24/7", "3rd generación", "4th generación", "5th generación", "6th generación", "analizada", "asimétrica", "asíncrona", "monitorizada por red", "bidireccional", "bifurcada", "generada por el cliente", "cliente servidor", "coherente", "cohesiva", "compuesto", "sensible al contexto", "basado en el contexto", "basado en contenido", "dedicada", "generado por la demanda", "didactica", "direccional", "discreta", "dinámica", "potenciada", "acompasada", "ejecutiva", "explícita", "tolerante a fallos", "innovadora", "amplio ábanico", "global", "heurística", "alto nivel", "holística", "homogénea", "hibrida", "incremental", "intangible", "interactiva", "intermedia", "local", "logística", "maximizada", "metódica", "misión crítica", "móbil", "modular", "motivadora", "multimedia", "multiestado", "multitarea", "nacional", "basado en necesidades", "neutral", "nueva generación", "no-volátil", "orientado a objetos", "óptima", "optimizada", "radical", "tiempo real", "recíproca", "regional", "escalable", "secundaria", "orientada a soluciones", "estable", "estatica", "sistemática", "sistémica", "tangible", "terciaria", "transicional", "uniforme", "valor añadido", "vía web", "defectos cero", "tolerancia cero" };

pub const name_pattern = [_][]const u8{ "{{person.last_name}} {{company.suffix}}", "{{person.last_name}} y {{person.last_name}}", "{{person.last_name}} {{person.last_name}} {{company.suffix}}", "{{person.last_name}}, {{person.last_name}} y {{person.last_name}} Asociados" };

pub const noun = [_][]const u8{ "habilidad", "acceso", "adaptador", "algoritmo", "alianza", "analista", "aplicación", "enfoque", "arquitectura", "archivo", "inteligencia artificial", "array", "actitud", "medición", "gestión presupuestaria", "capacidad", "desafío", "circuito", "colaboración", "complejidad", "concepto", "conglomeración", "contingencia", "núcleo", "fidelidad", "base de datos", "data-warehouse", "definición", "emulación", "codificar", "encriptar", "extranet", "firmware", "flexibilidad", "focus group", "previsión", "base de trabajo", "función", "funcionalidad", "Interfaz Gráfica", "groupware", "Interfaz gráfico de usuario", "hardware", "Soporte", "jerarquía", "conjunto", "implementación", "infraestructura", "iniciativa", "instalación", "conjunto de instrucciones", "interfaz", "intranet", "base del conocimiento", "red de area local", "aprovechar", "matrices", "metodologías", "middleware", "migración", "modelo", "moderador", "monitorizar", "arquitectura abierta", "sistema abierto", "orquestar", "paradigma", "paralelismo", "política", "portal", "estructura de precios", "proceso de mejora", "producto", "productividad", "proyecto", "proyección", "protocolo", "línea segura", "software", "solución", "estandardización", "estrategia", "estructura", "éxito", "superestructura", "soporte", "sinergia", "mediante", "marco de tiempo", "caja de herramientas", "utilización", "website", "fuerza de trabajo" };

pub const suffix = [_][]const u8{ "S.L.", "e Hijos", "S.A.", "Hermanos" };
