pub const city_name = [_][]const u8{ "An Nhơn", "Biên Hòa", "Buôn Ma Thuột", "Bắc Ninh", "Cà Mau", "Cần Thơ", "Haiphong", "Hanoi", "Ho Chi Minh City", "Huế", "Hải Dương", "Long Xuyên", "Mỹ Tho", "Nam Định", "Nghi Sơn", "Nha Trang", "Phan Thiết", "Quy Nhơn", "Quảng Hà", "Sóc Trăng", "Thanh Hóa", "Thái Bình", "Thái Nguyên", "Thủ Dầu Một", "Thủ Đức", "Tân An", "Tân Uyên", "Vinh", "Việt Trì", "Vũng Tàu" };

pub const city_pattern = [_][]const u8{"{{location.city_name}}"};

pub const country = [_][]const u8{ "Afghanistan", "Ai Cập", "Albania", "Algérie", "Andorra", "Angola", "Vương quốc Liên hiệp Anh và Bắc Ireland", "Antigua và Barbuda", "Áo", "Ả Rập Xê Út", "Argentina", "Armenia", "Azerbaijan", "Ấn Độ", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belize", "Bénin", "Bhutan", "Bỉ", "Bolivia", "Bosna và Hercegovina", "Botswana", "Bồ Đào Nha", "Bờ Biển Ngà", "Brasil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Các Tiểu Vương quốc Ả Rập Thống nhất", "Cameroon", "Campuchia", "Canada", "Chile", "Colombia", "Comoros", "Cộng hòa Congo", "Cộng hòa Dân chủ Congo", "Costa Rica", "Croatia", "Cuba", "Djibouti", "Dominica", "Cộng hòa Dominica", "Đan Mạch", "Đông Timor", "Đức", "Ecuador", "El Salvador", "Eritrea", "Estonia", "Ethiopia", "Fiji", "Gabon", "Gambia", "Ghana", "Grenada", "Gruzia", "Guatemala", "Guiné-Bissau", "Guinea Xích Đạo", "Guinée", "Guyana", "Haiti", "Hà Lan", "Hàn Quốc", "Hoa Kỳ", "Honduras", "Hungary", "Hy Lạp", "Iceland", "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Jamaica", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait", "Kyrgyzstan", "Lào", "Latvia", "Lesotho", "Liban", "Liberia", "Libya", "Liechtenstein", "Litva", "Luxembourg", "Macedonia", "Madagascar", "Malaysia", "Mali", "Malta", "Maroc", "Quần đảo Marshall", "Mauritanie", "Mauritius", "México", "Micronesia", "Moldova", "Monaco", "Mông Cổ", "Montenegro", "Mozambique", "Myanmar", "Namibia", "Nam Sudan", "Nam Phi", "Nauru", "Na Uy", "Nepal", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Nga", "Nhật Bản", "Oman", "Pakistan", "Palau", "Palestine", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Pháp", "Phần Lan", "Philippines", "Qatar", "România", "Rwanda", "Saint Kitts và Nevis", "Saint Lucia", "Saint Vincent và Grenadines", "Samoa", "San Marino", "São Tomé và Príncipe", "Séc", "Sénégal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Síp", "Slovakia", "Slovenia", "Solomon", "Somalia", "Sri Lanka", "Sudan", "Suriname", "Swaziland", "Syria", "Tajikistan", "Tanzania", "Tây Ban Nha", "Tchad", "Thái Lan", "Thổ Nhĩ Kỳ", "Thụy Điển", "Thụy Sĩ", "Togo", "Tonga", "Triều Tiên", "Trinidad và Tobago", "Trung Quốc", "Trung Phi", "Tunisia", "Turkmenistan", "Tuvalu", "Úc", "Uganda", "Ukraina", "Uruguay", "Uzbekistan", "Vanuatu", "Vatican", "Venezuela", "Việt Nam", "Ý", "Yemen", "Zambia", "Zimbabwe" };

pub const default_country = [_][]const u8{"Việt Nam"};

pub const postcode = [_][]const u8{"#####"};

pub const state = [_][]const u8{ "An Giang", "Bà Rịa-Vũng Tàu", "Bắc Giang", "Bắc Kạn", "Bạc Liêu", "Bắc Ninh", "Bến Tre", "Bình Định", "Bình Dương", "Bình Phước", "Bình Thuận", "Cà Mau", "Cần Thơ", "Cao Bằng", "Đà Nẵng", "Đắk Lắk", "Đắk Nông", "Điện Biên", "Đồng Nai", "Đồng Tháp", "Gia Lai", "Hà Giang", "Hà Nam", "Hà Tây", "Hà Tĩnh", "Hải Dương", "Hải Phòng", "Hà Nội", "Hậu Giang", "Hồ Chí Minh", "Hòa Bình", "Hưng Yên", "Khánh Hòa", "Kiên Giang", "Kon Tum", "Lai Châu", "Lâm Đồng", "Lạng Sơn", "Lào Cai", "Long An", "Nam Định", "Nghệ An", "Ninh Bình", "Ninh Thuận", "Phú Thọ", "Phú Yên", "Quảng Bình", "Quảng Nam", "Quảng Ngãi", "Quảng Ninh", "Quảng Trị", "Sóc Trăng", "Sơn La", "Tây Ninh", "Thái Bình", "Thái Nguyên", "Thanh Hóa", "Thừa Thiên-Huế", "Tiền Giang", "Trà Vinh", "Tuyên Quang", "Vĩnh Long", "Vĩnh Phúc", "Yên Bái" };

pub const street_pattern = [_][]const u8{ "{{person.firstName}} {{location.street_suffix}}", "{{person.lastName}} {{location.street_suffix}}" };
