const NamePattern = @import("../../modules/person.zig").NamePattern;

pub const female_first_name = [_][]const u8{ "Agnes", "Alberte", "Alexandrea", "Alice", "Alma", "Amanda", "Anita", "Anna", "Anne", "Annette", "Astrid", "Bente", "Betina", "Birgitte", "Britt", "Camilla", "Caroline", "Cecilie", "Charlotte", "Christina", "Clara", "Ditte-Marie", "Dorit", "Dorthe", "Ea", "Elisabeth", "Elise", "Ella", "Ellen-Margrethe", "Else", "Emilie", "Emma", "Eva", "Fatima", "Freja", "Frida", "Gitte", "Gry", "Hanne", "Hedvig", "Helene", "Helle", "Hilda", "Ida", "Ingrid", "Isabella", "Janni", "Jeanette", "Jette", "Johanne", "Josefine", "Julie", "Karen", "Karla", "Kathrine", "Katrine", "Kirsten", "Laila", "Lene", "Lillian", "Line", "Lis", "Lisa", "Lisbeth", "Liv", "Lone", "Louise", "Luna", "Lykke", "Maja", "Malene", "Maren", "Maria", "Marianne", "Mathilde", "Merete", "Mette", "Mia", "Mille", "Mona", "Nadia", "Nanna", "Nicoline", "Nina", "Pia", "Rebecca", "Regitze", "Rikke", "Rosa-Maria", "Ruth", "Sabrina", "Sandra", "Sanne", "Sara", "Sarah", "Signe", "Silje", "Simone", "Sofie", "Stine", "Susanne", "Therese", "Tina", "Tine", "Trine", "Vibeke", "Viktoria", "Yasmin", "Zara" };

pub const female_middle_name = [_][]const u8{ "Birk", "Bjerg", "Bjerre", "Bundgaard", "Dahl", "Dal", "Dam", "Feldt", "Frost", "Grøn", "Hald", "Hjorth", "Holm", "Husum", "Jul", "Kjær", "Klit", "Koch", "Krog", "Linde", "Lund", "Mose", "Mølgaard", "Nord", "Præst", "Rosen", "Skov", "Smed", "Vestergaard", "Østergaard" };

pub const female_prefix = [_][]const u8{"fr."};

pub const first_name = [_][]const u8{ "Adam", "Adrian", "Agnes", "Ahmad", "Aksel", "Albert", "Alberte", "Alexander", "Alexandrea", "Alfred", "Ali", "Alice", "Alma", "Amanda", "Anders", "Andreas", "Anita", "Anna", "Anne", "Annette", "Anton", "Arthur", "Arunthavanathan", "Astrid", "August", "Benjamin", "Bente", "Betina", "Birgitte", "Bjørn", "Brian", "Britt", "Camilla", "Carl", "Caroline", "Cecilie", "Charlotte", "Christian", "Christina", "Christopher", "Clara", "Claus", "Daniel", "David", "Ditte-Marie", "Dorit", "Dorthe", "Ea", "Elias", "Elisabeth", "Elise", "Ella", "Ellen-Margrethe", "Elliot", "Else", "Emil", "Emilie", "Emma", "Erik", "Esben", "Eva", "Fatima", "Felix", "Frank", "Frederik", "Freja", "Frida", "Georg", "Gitte", "Gry", "Hakim", "Hanne", "Hans", "Harald", "Hedvig", "Helene", "Helle", "Henrik", "Hilda", "Ib", "Ida", "Ingrid", "Isabella", "Ivan", "Jacob", "Jakob", "Jan", "Janni", "Jeanette", "Jens", "Jeppe", "Jesper", "Jette", "Johan", "Johanne", "John", "Jonas", "Jonathan", "Josefine", "Julie", "Jørgen", "Kaj", "Karen", "Karl", "Karl-Emil", "Karl-Johan", "Karla", "Kasper", "Kathrine", "Katrine", "Kevin", "Kim", "Kirsten", "Kurt", "Laila", "Lars", "Lasse", "Leif", "Lene", "Leo", "Lillian", "Line", "Linus", "Lis", "Lisa", "Lisbeth", "Liv", "Lone", "Louise", "Lucas", "Lukas", "Luna", "Lykke", "Mads", "Magnus", "Maja", "Malene", "Malthe", "Maren", "Maria", "Marianne", "Mark", "Martin", "Mathias", "Mathilde", "Mathis", "Max", "Merete", "Mette", "Mia", "Michael", "Mikkel", "Mille", "Mohammad", "Mona", "Morten", "Nadia", "Nanna", "Nicklas", "Nicoline", "Niels", "Niels-Christian", "Niklas", "Nina", "Noah", "Ole", "Oliver", "Oscar", "Otto", "Patrick", "Per", "Peter", "Philip", "Pia", "Poul", "Rasmus", "Rebecca", "Regitze", "Rikke", "Robert", "Rosa-Maria", "Ruth", "Sabrina", "Samuel", "Sandra", "Sanne", "Sara", "Sarah", "Sebastian", "Signe", "Sigurd", "Silje", "Simon", "Simone", "Sofie", "Steen", "Stefan", "Stig", "Stine", "Sune", "Susanne", "Svend", "Søren", "Theo", "Therese", "Thomas", "Tim", "Tina", "Tine", "Tobias", "Trine", "Troels", "Uffe", "Ulrik", "Vagn", "Valdemar", "Vibeke", "Victor", "Viggo", "Viktor", "Viktoria", "Vilhelm", "Villy", "Vincent", "William", "Yasmin", "Zara" };

pub const last_name = [_][]const u8{ "Abbas", "Abdi", "Andersen", "Andresen", "Bak", "Bang", "Bech", "Beckmann", "Berg", "Bertelsen", "Bisgaard", "Bjerregaard", "Blom", "Bonde", "Brandt", "Brix", "Bruun", "Buch", "Buhl", "Bundgaard", "Carlsen", "Christensen", "Christiansen", "Clausen", "Dahl", "Dalgaard", "Dam", "Damm", "Davidsen", "Dupont", "Esbensen", "Fischer", "Foged", "Frandsen", "Frederiksen", "Gade", "Garcia", "Gregersen", "Hald", "Hansen", "Haugaard", "Hedegaard", "Henriksen", "Hermansen", "Hjort", "Hjorth", "Holm", "Iversen", "Jakobsen", "Jensen", "Jeppesen", "Jespersen", "Johannessen", "Johannsen", "Johansen", "Juhl", "Justesen", "Jørgensen", "Karlsen", "Khan", "Kjeldsen", "Kjær", "Klausen", "Knudsen", "Kristensen", "Krogh", "Larsen", "Lauridsen", "Laursen", "Lorentzen", "Lund", "Madsen", "Magnussen", "Marcussen", "Mortensen", "Munch", "Munk", "Møller", "Nguyen", "Nielsen", "Nissen", "Nygaard", "Olsen", "Pallesen", "Pedersen", "Petersen", "Pham", "Poulsen", "Rasmussen", "Ravn", "Richter", "Schmidt", "Schrøder", "Simonsen", "Skov", "Steffensen", "Storm", "Svendsen", "Svensson", "Sørensen", "Thomsen", "Toft", "Vestergaard", "Villadsen", "Vinther", "Winther" };

pub const last_name_pattern = [_]NamePattern{ .{ .value = "{{person.last_name}}", .weight = 95 }, .{ .value = "{{person.last_name}}-{{person.last_name}}", .weight = 5 } };

pub const male_first_name = [_][]const u8{ "Adam", "Adrian", "Ahmad", "Aksel", "Albert", "Alexander", "Alfred", "Ali", "Anders", "Andreas", "Anton", "Arthur", "Arunthavanathan", "August", "Benjamin", "Bjørn", "Brian", "Carl", "Christian", "Christopher", "Claus", "Daniel", "David", "Elias", "Elliot", "Emil", "Erik", "Esben", "Felix", "Frank", "Frederik", "Georg", "Hakim", "Hans", "Harald", "Henrik", "Ib", "Ivan", "Jacob", "Jakob", "Jan", "Jens", "Jeppe", "Jesper", "Johan", "John", "Jonas", "Jonathan", "Jørgen", "Kaj", "Karl-Emil", "Karl-Johan", "Karl", "Kasper", "Kevin", "Kim", "Kurt", "Lars", "Lasse", "Leif", "Leo", "Linus", "Lucas", "Lukas", "Mads", "Magnus", "Malthe", "Mark", "Martin", "Mathias", "Mathis", "Max", "Michael", "Mikkel", "Mohammad", "Morten", "Nicklas", "Niels-Christian", "Niels", "Niklas", "Noah", "Ole", "Oliver", "Oscar", "Otto", "Patrick", "Per", "Peter", "Philip", "Poul", "Rasmus", "Robert", "Samuel", "Sebastian", "Sigurd", "Simon", "Steen", "Stefan", "Stig", "Sune", "Svend", "Søren", "Theo", "Thomas", "Tim", "Tobias", "Troels", "Uffe", "Ulrik", "Vagn", "Valdemar", "Victor", "Viggo", "Viktor", "Vilhelm", "Villy", "Vincent", "William" };

pub const male_middle_name = [_][]const u8{ "Birk", "Bjerg", "Bjerre", "Bundgaard", "Dahl", "Dal", "Dam", "Feldt", "Frost", "Grøn", "Hald", "Hjorth", "Holm", "Husum", "Jul", "Kjær", "Klit", "Koch", "Krog", "Linde", "Lund", "Mose", "Mølgaard", "Nord", "Præst", "Rosen", "Skov", "Smed", "Vestergaard", "Østergaard" };

pub const male_prefix = [_][]const u8{"hr."};

pub const middle_name = [_][]const u8{ "Birk", "Bjerg", "Bjerre", "Bundgaard", "Dahl", "Dal", "Dam", "Feldt", "Frost", "Grøn", "Hald", "Hjorth", "Holm", "Husum", "Jul", "Kjær", "Klit", "Koch", "Krog", "Linde", "Lund", "Mose", "Mølgaard", "Nord", "Præst", "Rosen", "Skov", "Smed", "Vestergaard", "Østergaard" };

pub const name = [_]NamePattern{ .{ .value = "{{person.firstName}} {{person.lastName}}", .weight = 50 }, .{ .value = "{{person.firstName}} {{person.middleName}} {{person.lastName}}", .weight = 50 } };

pub const prefix = [_][]const u8{ "fr.", "hr." };

pub const sex = [_][]const u8{ "mand", "kvinde" };
