pub const adjective = [_][]const u8{ "aktiv", "akut", "alvorlig", "anderledes", "ansvarlig", "automatisk", "bekymret", "beslutsom", "betagende", "betydelig", "bevidst", "billig", "blød", "bred", "charmerende", "dynamisk", "dyr", "dårlig", "effektiv", "elegant", "energisk", "enestående", "enkel", "entusiastisk", "fantastisk", "farlig", "farverig", "fattig", "fleksibel", "flittig", "flydende", "forbløffende", "fordelagtig", "forfærdelig", "fornuftig", "forstående", "fremragende", "frisk", "frodig", "frugtbar", "fuldstændig", "følsom", "førsteklasses", "glad", "glamourøs", "grundig", "grusom", "gæv", "gådefuld", "hastig", "hensynsfuld", "hjertelig", "hurtig", "hård", "imponerende", "intelligent", "intens", "interessant", "ivrig", "kendt", "klog", "kold", "komfortabel", "kompleks", "konkurrencedygtig", "kraftfuld", "kreativ", "krydret", "kærlig", "larmende", "lav", "ledig", "let", "loyal", "lun", "lækker", "mager", "magtfuld", "meget", "mild", "modig", "mærkelig", "møjsommelig", "naturtro", "nyttig", "nødvendig", "nøjagtig", "omhyggelig", "omtænksom", "original", "overraskende", "parat", "positiv", "praktisk", "præcis", "rask", "rimelig", "rolig", "rund", "rå", "sammenhængende", "selvsikker", "sikker", "simpel", "sjov", "skarp", "skræmmende", "skøn", "slank", "smagfuld", "smuk", "snedig", "solid", "spændende", "stille", "stolt", "strålende", "stærk", "sund", "svag", "sød", "tapper", "tilfreds", "tilgængelig", "trofast", "trænet", "tydelig", "tålmodig", "uafhængig", "ubegrænset", "ubekymret", "uenig", "uformel", "uhindret", "uhøflig", "ulige", "ulykkelig", "umiddelbar", "umulig", "unik", "unnaturlig", "usædvanlig", "utrolig", "utålmodig", "varm", "venlig", "vigtig", "vild", "virkelig", "vis", "vittig", "ægte", "ærgerlig", "øm", "ønskelig", "åben", "åbenhjertig" };

pub const adverb = [_][]const u8{ "aldrig", "allerede", "altid", "andensteds", "baglæns", "bestemt", "derefter", "endelig", "forbi", "forgæves", "først", "hastigt", "heldigvis", "her", "igen", "imidlertid", "imorgen", "indimellem", "jo", "kun", "lige", "meget", "måske", "næppe", "næsten", "ofte", "også", "omhyggeligt", "overalt", "pludselig", "sammen", "sandsynligvis", "selvfølgelig", "snart", "stadig", "straks", "tit", "udenfor", "undervejs", "uskadt", "vanligvis" };

pub const conjunction = [_][]const u8{ "altså", "at", "da", "der", "dog", "efter", "efterhånden", "eller", "end", "enten", "for", "fordi", "før", "hvad", "hvem", "hvis", "hvor", "hvordan", "hvorfor", "hvorvidt", "idet", "imens", "indtil", "ligesom", "men", "mens", "når", "og", "om", "selvom", "siden", "skønt", "som", "så" };

pub const interjection = [_][]const u8{ "ah", "av", "haha", "hallo", "hej", "hov", "hurra", "ih", "ja", "nej", "oh", "pyha", "tja", "uf", "uh", "wow", "æv", "øv" };

pub const noun = [_][]const u8{ "afsnit", "afstand", "aften", "alderdom", "antal", "arbejde", "artikel", "avis", "bad", "balkon", "bank", "bar", "barn", "beslutning", "betydning", "bibliotek", "bil", "billede", "billet", "bjerg", "blomst", "blyant", "bog", "bord", "bredde", "brev", "bro", "bund", "butik", "by", "bygning", "børnehave", "cafe", "center", "chance", "computer", "cykel", "dag", "dal", "del", "dybde", "dør", "effekt", "efterår", "elevator", "erhverv", "farve", "fase", "ferie", "fest", "film", "fisk", "fjernsyn", "flade", "flod", "folk", "forår", "fugl", "funktion", "fødsel", "gade", "galakse", "grund", "gruppe", "gulv", "hav", "have", "havn", "historie", "hjørne", "hospital", "hotel", "hund", "hus", "højde", "indhold", "institution", "job", "kant", "kapitel", "karriere", "kat", "kategori", "kilde", "kirke", "klasse", "klima", "klub", "konsekvens", "konto", "kort", "kredit", "kulde", "kultur", "kunst", "kælder", "køkken", "land", "lejlighed", "linje", "liv", "lufthavn", "lyn", "længde", "løsning", "lån", "magasin", "maleri", "metode", "middag", "miljø", "minut", "morgen", "moske", "mulighed", "museum", "musik", "myndighed", "mængde", "mønt", "mål", "måne", "måned", "nat", "nation", "natur", "ord", "organisation", "papir", "park", "pen", "penge", "planet", "pris", "problem", "proces", "profession", "punkt", "radio", "regering", "regn", "restaurant", "resultat", "retning", "risiko", "rolle", "rum", "samfund", "scene", "seddel", "sekund", "selskab", "serie", "side", "skole", "skov", "skulptur", "sky", "sne", "sol", "sommer", "soveværelse", "spil", "spørgsmål", "stat", "station", "stjerne", "stol", "storm", "strand", "stue", "størrelse", "supermarked", "svar", "synagoge", "system", "sætning", "sø", "tag", "teater", "tegning", "tempel", "temperatur", "terrasse", "tid", "time", "top", "torden", "tradition", "trappe", "trin", "træ", "tunnel", "type", "udstilling", "uge", "ungdom", "univers", "universitet", "valg", "varme", "vej", "vejr", "video", "vind", "vindue", "vinter", "virksomhed", "voksen", "væg", "vægt", "værdi", "ø", "år", "årsag", "årstid" };

pub const preposition = [_][]const u8{ "ad", "af", "bag", "efter", "for", "fra", "før", "gennem", "henover", "hos", "i", "imod", "langs", "med", "mellem", "mod", "om", "omkring", "over", "på", "til", "tværs", "uden", "under", "ved" };

pub const verb = [_][]const u8{ "absorbere", "acceptere", "anbefale", "anerkende", "anmelde", "anmode", "anvende", "arbejde", "besøge", "betale", "bo", "bruge", "brænde", "bygge", "bære", "bøje", "cykle", "danne", "danse", "deltage", "diskutere", "drikke", "drive", "drømme", "dykke", "elske", "estimere", "etablere", "falde", "fange", "finde", "fjerne", "forstå", "forsøge", "føle", "få", "gemme", "gide", "give", "gnide", "gøgle", "gøre", "gå", "have", "hjælpe", "holde", "høre", "kalde", "knipse", "koge", "komme", "kunne", "købe", "lave", "leve", "lytte", "lære", "læse", "løbe", "løfte", "male", "mene", "miste", "motivere", "møde", "måle", "nive", "nyde", "nægte", "nævne", "pege", "pjække", "plante", "plukke", "prøve", "pynte", "rejse", "ringe", "rive", "se", "sige", "skrive", "sove", "spille", "spise", "spørge", "starte", "svømme", "synes", "synge", "sætte", "søge", "tage", "tale", "tjene", "træne", "tænke", "udforske", "udføre", "udgive", "udleje", "undervise", "vandre", "vide", "ville", "vise", "vokse", "vælge", "være", "ønske" };
