const NamePattern = @import("../../modules/person.zig").NamePattern;

pub const female_first_name = [_][]const u8{ "Adriana", "Alexandra", "Alice", "Amélia", "Ana", "Ariana", "Áurea", "Aurora", "Bárbara", "Beatriz", "Benedita", "Bruna", "Caetana", "Camila", "Carla", "Carlota", "Carminho", "Carmo", "Carolina", "Catarina", "Cecília", "Célia", "Clara", "Constança", "Daniela", "Débora", "Diana", "Eduarda", "Elisa", "Ema", "Emília", "Érica", "Eva", "Fabiana", "Filipa", "Flor", "Francisca", "Frederica", "Gabriela", "Helena", "Inês", "Irina", "Íris", "Isabel", "Jéssica", "Joana", "Júlia", "Juliana", "Julieta", "Lara", "Laura", "Leonor", "Letícia", "Lia", "Lorena", "Luana", "Luena", "Luísa", "Luna", "Madalena", "Mafalda", "Mara", "Márcia", "Margarida", "Maria", "Mariana", "Marta", "Matilde", "Melissa", "Mia", "Miriam", "Natália", "Nicole", "Núria", "Ofélia", "Olívia", "Paula", "Pilar", "Rafaela", "Raquel", "Rita", "Rosa", "Safira", "Sara", "Sílvia", "Sofia", "Soraia", "Tatiana", "Teresa", "Valentina", "Vânia", "Vera", "Vitória" };

pub const female_prefix = [_][]const u8{ "Sra.", "Dra.", "Prof.ª", "Eng.ª" };

pub const first_name = [_][]const u8{ "Adriana", "Afonso", "Alexandra", "Alexandre", "Alice", "Amélia", "Ana", "André", "Ângelo", "António", "Ariana", "Artur", "Áurea", "Aurora", "Bárbara", "Beatriz", "Benedita", "Benjamim", "Bernardo", "Bruna", "Bruno", "Caetana", "Camila", "Carla", "Carlos", "Carlota", "Carminho", "Carmo", "Carolina", "Catarina", "Cecília", "Célia", "César", "Clara", "Constança", "Cristiano", "Daniel", "Daniela", "David", "Débora", "Diana", "Dinis", "Diogo", "Duarte", "Edgar", "Eduarda", "Eduardo", "Elias", "Elisa", "Ema", "Emanuel", "Emília", "Érica", "Eva", "Fabiana", "Fábio", "Feliciano", "Fernando", "Filipa", "Filipe", "Flor", "Francisca", "Francisco", "Frederica", "Frederico", "Gabriel", "Gabriela", "Gaspar", "Gil", "Gonçalo", "Guilherme", "Gustavo", "Helena", "Hélio", "Henrique", "Hugo", "Igor", "Ígor", "Inês", "Irina", "Íris", "Isabel", "Isac", "Ivan", "Ivo", "Jaime", "Jéssica", "Joana", "João", "Joaquim", "Jorge", "José", "Josué", "Júlia", "Juliana", "Julieta", "Júlio", "Lara", "Laura", "Leandro", "Leonardo", "Leonor", "Letícia", "Lia", "Lorena", "Lourenço", "Luana", "Lucas", "Luena", "Luís", "Luísa", "Luna", "Madalena", "Mafalda", "Manel", "Manuel", "Mara", "Marcelo", "Márcia", "Marco", "Marcos", "Margarida", "Maria", "Mariana", "Mário", "Marta", "Martim", "Mateus", "Matias", "Matilde", "Mauro", "Melissa", "Mia", "Micael", "Miguel", "Miriam", "Moisés", "Natália", "Nicole", "Norberto", "Nuno", "Núria", "Ofélia", "Olívia", "Paula", "Paulo", "Pedro", "Pilar", "Rafael", "Rafaela", "Raquel", "Raul", "Renato", "Ricardo", "Rita", "Roberto", "Rodrigo", "Romeu", "Rosa", "Rúben", "Rui", "Safira", "Salvador", "Samuel", "Sandro", "Santiago", "Sara", "Sebastião", "Sérgio", "Sílvia", "Simão", "Sofia", "Soraia", "Tatiana", "Teresa", "Tiago", "Tomás", "Tomé", "Valentim", "Valentina", "Valter", "Vânia", "Vasco", "Vera", "Vicente", "Vítor", "Vitória", "Xavier" };

pub const last_name = [_][]const u8{ "Abreu", "Albuquerque", "Almeida", "Alves", "Amaral", "Amorim", "Andrade", "Anjos", "Antunes", "Araújo", "Assunção", "Azevedo", "Baptista", "Barbosa", "Barros", "Batista", "Borges", "Braga", "Branco", "Brito", "Campos", "Cardoso", "Carneiro", "Carvalho", "Castro", "Coelho", "Correia", "Costa", "Cruz", "Cunha", "Domingues", "Esteves", "Faria", "Fernandes", "Ferreira", "Figueiredo", "Fonseca", "Freitas", "Garcia", "Gaspar", "Gomes", "Gonçalves", "Guerreiro", "Henriques", "Jesus", "Leal", "Leite", "Lima", "Lopes", "Loureiro", "Lourenço", "Macedo", "Machado", "Magalhães", "Maia", "Marques", "Martins", "Matias", "Matos", "Melo", "Mendes", "Miranda", "Monteiro", "Morais", "Moreira", "Mota", "Moura", "Nascimento", "Neto", "Neves", "Nobre", "Nogueira", "Nunes", "Oliveira", "Pacheco", "Paiva", "Pereira", "Pinheiro", "Pinho", "Pinto", "Pires", "Ramos", "Raposo", "Reis", "Ribeiro", "Rocha", "Rodrigues", "Santos", "Saraiva", "Silva", "Simões", "Soares", "Sousa", "Sá", "Tavares", "Teixeira", "Torres", "Valente", "Vaz", "Vicente", "Vieira" };

pub const last_name_pattern = [_]NamePattern{.{ .value = "{{person.last_name}}", .weight = 1 }};

pub const male_first_name = [_][]const u8{ "Afonso", "Alexandre", "André", "Ângelo", "António", "Artur", "Benjamim", "Bernardo", "Bruno", "Carlos", "César", "Cristiano", "Daniel", "David", "Dinis", "Diogo", "Duarte", "Edgar", "Eduardo", "Elias", "Emanuel", "Fábio", "Feliciano", "Fernando", "Filipe", "Francisco", "Frederico", "Gabriel", "Gaspar", "Gil", "Gonçalo", "Guilherme", "Gustavo", "Hélio", "Henrique", "Hugo", "Igor", "Ígor", "Isac", "Ivan", "Ivo", "Jaime", "João", "Joaquim", "Jorge", "José", "Josué", "Júlio", "Leandro", "Leonardo", "Lourenço", "Lucas", "Luís", "Manel", "Manuel", "Marcelo", "Marco", "Marcos", "Mário", "Martim", "Mateus", "Matias", "Mauro", "Micael", "Miguel", "Moisés", "Norberto", "Nuno", "Paulo", "Pedro", "Rafael", "Raul", "Renato", "Ricardo", "Roberto", "Rodrigo", "Romeu", "Rúben", "Rui", "Salvador", "Samuel", "Sandro", "Santiago", "Sebastião", "Sérgio", "Simão", "Tiago", "Tomás", "Tomé", "Valentim", "Valter", "Vasco", "Vicente", "Vítor", "Xavier" };

pub const male_prefix = [_][]const u8{ "Sr.", "Dr.", "Prof.", "Eng.º" };

pub const name = [_]NamePattern{ .{ .value = "{{person.firstName}} {{person.lastName}}", .weight = 9 }, .{ .value = "{{person.prefix}} {{person.firstName}} {{person.lastName}}", .weight = 1 } };

pub const prefix = [_][]const u8{ "Dr.", "Dra.", "Eng.ª", "Eng.º", "Prof.", "Prof.ª", "Sr.", "Sra." };

pub const suffix = .{};
